from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_DB_PATH = ROOT_DIR / "database" / "pms_gmc.sqlite"


def database_url() -> str:
    return (os.environ.get("PMS_DATABASE_URL") or os.environ.get("DATABASE_URL") or "").strip()


def is_postgres_enabled() -> bool:
    value = database_url().lower()
    return value.startswith("postgres://") or value.startswith("postgresql://")


def database_backend() -> str:
    return "postgresql" if is_postgres_enabled() else "sqlite"


def database_display_name(db_path: Path | str | None = None) -> str:
    if is_postgres_enabled():
        return "PostgreSQL"
    return Path(db_path or DEFAULT_DB_PATH).name


class CompatRow(dict):
    def __init__(self, keys: list[str], values: tuple[Any, ...]):
        super().__init__(zip(keys, values))
        self._values = list(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


class PostgresCursor:
    def __init__(self, cursor, owner: "PostgresConnection"):
        self._cursor = cursor
        self._owner = owner

    def execute(self, sql: str, params: tuple | list | None = None):
        self._owner._execute_on_cursor(self._cursor, sql, params)
        return self

    def fetchone(self):
        row = self._cursor.fetchone()
        if row is None:
            return None
        keys = [column.name for column in self._cursor.description or []]
        return CompatRow(keys, tuple(row))

    def fetchall(self):
        rows = self._cursor.fetchall()
        keys = [column.name for column in self._cursor.description or []]
        return [CompatRow(keys, tuple(row)) for row in rows]

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount

    @property
    def lastrowid(self):
        return None

    def close(self) -> None:
        self._cursor.close()


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection
        self.total_changes = 0

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()

    def cursor(self) -> PostgresCursor:
        return PostgresCursor(self._connection.cursor(), self)

    def execute(self, sql: str, params: tuple | list | None = None) -> PostgresCursor:
        cursor = self.cursor()
        cursor.execute(sql, params)
        return cursor

    def executemany(self, sql: str, seq_of_params) -> PostgresCursor:
        cursor = self.cursor()
        query = convert_sql(sql)
        cursor._cursor.executemany(query, seq_of_params)
        if cursor.rowcount and cursor.rowcount > 0:
            self.total_changes += cursor.rowcount
        return cursor

    def executescript(self, script: str) -> None:
        for statement in split_sql_script(script):
            self.execute(statement)

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()

    def _execute_on_cursor(self, cursor, sql: str, params: tuple | list | None = None) -> None:
        special = execute_special_postgres(cursor, sql, params)
        if special:
            return
        query = convert_sql(sql)
        cursor.execute(query, tuple(params or ()))
        if cursor.rowcount and cursor.rowcount > 0:
            self.total_changes += cursor.rowcount


def split_sql_script(script: str) -> list[str]:
    statements = []
    current = []
    in_single = False
    in_double = False
    previous = ""
    for char in script:
        if char == "'" and not in_double and previous != "\\":
            in_single = not in_single
        elif char == '"' and not in_single and previous != "\\":
            in_double = not in_double
        if char == ";" and not in_single and not in_double:
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
        else:
            current.append(char)
        previous = char
    statement = "".join(current).strip()
    if statement:
        statements.append(statement)
    return statements


def convert_sql(sql: str) -> str:
    query = str(sql).strip()
    if not query:
        return query
    if query.upper().startswith("PRAGMA FOREIGN_KEYS"):
        return "SELECT 1"
    query = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        query,
        flags=re.I,
    )
    query = re.sub(
        r"\bCREATE\s+VIEW\s+IF\s+NOT\s+EXISTS\s+([A-Za-z0-9_\".]+)\s+AS\b",
        r"CREATE OR REPLACE VIEW \1 AS",
        query,
        flags=re.I,
    )
    if re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", query, flags=re.I):
        query = re.sub(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", query, flags=re.I)
        if "ON CONFLICT" not in query.upper():
            query = query.rstrip(";") + " ON CONFLICT DO NOTHING"
    query = query.replace("?", "%s")
    return query


def normalized_identifier(value: str) -> str:
    return str(value or "").strip().strip('"').strip("'")


def execute_special_postgres(cursor, sql: str, params: tuple | list | None = None) -> bool:
    query = str(sql).strip()
    upper = query.upper()
    if upper.startswith("PRAGMA TABLE_INFO"):
        match = re.search(r"PRAGMA\s+table_info\((.+)\)", query, re.I)
        table_name = normalized_identifier(match.group(1) if match else "")
        cursor.execute(
            """
            SELECT column_name AS name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = %s
            ORDER BY ordinal_position
            """,
            (table_name,),
        )
        return True
    if upper.startswith("PRAGMA INDEX_LIST"):
        match = re.search(r"PRAGMA\s+index_list\((.+)\)", query, re.I)
        table_name = normalized_identifier(match.group(1) if match else "")
        cursor.execute(
            """
            SELECT conname AS name, 1 AS unique
            FROM pg_constraint
            WHERE conrelid = %s::regclass
              AND contype IN ('p', 'u')
            """,
            (table_name,),
        )
        return True
    if upper.startswith("PRAGMA INDEX_INFO"):
        match = re.search(r"PRAGMA\s+index_info\((.+)\)", query, re.I)
        index_name = normalized_identifier(match.group(1) if match else "")
        cursor.execute(
            """
            SELECT a.attname AS name
            FROM pg_constraint c
            JOIN unnest(c.conkey) WITH ORDINALITY AS cols(attnum, ord) ON true
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = cols.attnum
            WHERE c.conname = %s
            ORDER BY cols.ord
            """,
            (index_name,),
        )
        return True
    if "FROM SQLITE_MASTER" in upper:
        if "TYPE IN ('TABLE', 'VIEW')" in upper:
            cursor.execute(
                """
                SELECT table_name AS name,
                       CASE WHEN table_type = 'VIEW' THEN 'view' ELSE 'table' END AS type
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type IN ('BASE TABLE', 'VIEW')
                ORDER BY CASE WHEN table_type = 'BASE TABLE' THEN 0 ELSE 1 END, table_name
                """
            )
            return True
        match = re.search(r"name\s*=\s*'([^']+)'", query, re.I)
        table_name = match.group(1) if match else ""
        cursor.execute(
            """
            SELECT table_name AS name
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = %s
            """,
            (table_name,),
        )
        return True
    if upper.startswith("SELECT LAST_INSERT_ROWID()"):
        cursor.execute("SELECT LASTVAL() AS id")
        return True
    return False


def open_database_connection(db_path: Path | str | None = None):
    if is_postgres_enabled():
        try:
            import psycopg
        except ImportError as exc:
            raise RuntimeError(
                "La variable DATABASE_URL est definie, mais le paquet psycopg n'est pas installe."
            ) from exc
        return PostgresConnection(psycopg.connect(database_url(), connect_timeout=10))

    path = Path(db_path or DEFAULT_DB_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(path, timeout=30)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def table_exists(conn, table_name: str) -> bool:
    row = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table' AND name = ?
        """,
        (table_name,),
    ).fetchone()
    return bool(row)


def table_columns(conn, table_name: str) -> list[dict]:
    clean_name = normalized_identifier(table_name)
    return [dict(row) for row in conn.execute(f"PRAGMA table_info({quote_identifier(clean_name)})").fetchall()]


def quote_identifier(identifier: str) -> str:
    return f'"{str(identifier).replace(chr(34), chr(34) + chr(34))}"'


def database_objects(conn) -> list[dict]:
    return [
        dict(row)
        for row in conn.execute(
            """
            SELECT name, type
            FROM sqlite_master
            WHERE type IN ('table', 'view')
              AND name NOT LIKE 'sqlite_%'
            ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name
            """
        ).fetchall()
    ]


DatabaseError = sqlite3.DatabaseError
