(function () {
  const data = {
    sourceFiles: [
      {
        name: "Catalogue_et_Guide_methodologique_KPI_Palladium_Africa_2026.xlsx",
        role: "Catalogue KPI et guide methodologique",
      },
      {
        name: "GMC_FICHE_COLLECTE_V2.xlsx",
        role: "Fiches KoboCollect et dictionnaire des formules",
      },
      {
        name: "CDC_PMS_GMC_Group_2026.docx",
        role: "Cahier des charges PMS",
      },
    ],

    catalogSummary: {
      kpiCount: 74,
      formulaCount: 44,
      groupCount: 11,
      collectionDomains: 7,
      extractionDate: "24 juin 2026",
      categories: [
        { name: "DGA Business & Expansion", count: 43 },
        { name: "DGA Support & Performance", count: 23 },
        { name: "Direction Generale", count: 8 },
      ],
      frequencies: [
        { name: "Hebdo / Mensuel / Trimestriel / Annuel", count: 48 },
        { name: "Hebdomadaire / Mensuelle", count: 14 },
        { name: "Mensuelle", count: 6 },
        { name: "Mensuelle / Trimestrielle / Annuelle", count: 4 },
        { name: "Hebdomadaire", count: 2 },
      ],
    },

    objectiveKoboTemplate: {
      sourceFile: "Catalogue_et_Guide_methodologique_KPI_Palladium_Africa_2026.xlsx",
      catalogSheet: "Catalogue KPI",
      modelSheet: "Fiche KPI modele",
      catalogKpiCount: 74,
      requiredFields: [
        { key: "kpi_id", label: "ID KPI", source: "ID KPI", block: "Identification" },
        { key: "intitule_kpi", label: "Intitule du KPI", source: "Intitule du KPI", block: "Identification" },
        { key: "pole_id", label: "Pole / groupe", source: "Groupe de rattachement", block: "Rattachement" },
        { key: "definition_kpi", label: "Definition complete", source: "Description / Definition", block: "Definition" },
        { key: "type_kpi", label: "Type KPI", source: "Type de KPI", block: "Definition" },
        { key: "unite_mesure", label: "Unite de mesure", source: "Unite de mesure", block: "Calcul" },
        { key: "formule_calcul", label: "Formule de calcul", source: "Formule de calcul", block: "Calcul" },
        { key: "objectif_kpi", label: "Valeur cible", source: "Valeur cible", block: "Calcul" },
        { key: "frequence_collecte", label: "Frequence collecte", source: "Frequence de collecte", block: "Donnees" },
        { key: "periodicite_reporting", label: "Periodicite reporting", source: "Periodicite du reporting", block: "Donnees" },
        { key: "source_donnee", label: "Source de la donnee", source: "Source de la donnee", block: "Donnees" },
        { key: "responsable_kpi", label: "Owner KPI", source: "Responsable du KPI", block: "Responsabilite" },
        { key: "repondant", label: "Producteur donnee", source: "Repondant", block: "Responsabilite" },
        { key: "validateur", label: "Validateur", source: "Validateur", block: "Responsabilite" },
        { key: "validation_hierarchique", label: "Validation hierarchique", source: "Validation hierarchique", block: "Tracabilite" },
        { key: "statut_documentaire", label: "Statut documentaire", source: "Statut documentaire", block: "Tracabilite" },
        { key: "reference_source", label: "Reference source", source: "Reference source", block: "Tracabilite" },
        { key: "points_attention", label: "Points d'attention", source: "Points d'attention", block: "Tracabilite" },
      ],
      calculationFields: [
        { key: "pole_id", label: "Pole concerne", source: "Pole responsable de la donnee", block: "Rattachement" },
        { key: "kpi_id", label: "KPI a calculer", source: "Lien avec le formulaire KPI", block: "Rattachement" },
        { key: "periode_reporting", label: "Periode de reporting", source: "Mois, semaine ou trimestre", block: "Temps" },
        { key: "element_id", label: "Element de calcul", source: "Variable utilisee dans la formule", block: "Calcul" },
        { key: "valeur_element", label: "Valeur collectee", source: "Numerateur, denominateur ou valeur brute", block: "Calcul" },
        { key: "unite_mesure", label: "Unite de la valeur", source: "Pourcentage, montant, nombre, minutes", block: "Calcul" },
        { key: "filiale", label: "Filiale / pays", source: "Perimetre de consolidation", block: "Perimetre" },
        { key: "date_collecte", label: "Date de collecte", source: "Horodatage metier", block: "Tracabilite" },
        { key: "source_donnee", label: "Source de la donnee", source: "Systeme, fichier ou responsable", block: "Tracabilite" },
        { key: "validation_hierarchique", label: "Validation", source: "Controle avant calcul PMS", block: "Tracabilite" },
      ],
      koboLogicSteps: [
        "Formulaire 1 : declare les KPI, poles, objectifs et formules de calcul.",
        "Formulaire 2 : collecte les elements bruts necessaires a ces formules.",
        "La plateforme rapproche les deux formulaires par pole, KPI et periode.",
        "Le PMS calcule ensuite les valeurs KPI et alimente les tableaux de bord par pole.",
      ],
      referentials: {
        types: ["Financier", "Commercial", "Productivite", "Qualite", "Satisfaction Client", "Operationnel", "Strategique"],
        units: ["% (Pourcentage)", "Nombre / Quantite", "Montant (FCFA / XOF)", "Minutes", "Jours", "Autre"],
        frequencies: ["Hebdomadaire", "Mensuelle", "Trimestrielle", "Semestrielle", "Annuelle"],
        statuses: ["Brouillon", "A preciser", "A valider", "Actif", "Suspendu", "Archive"],
        validations: ["Oui", "Non", "Sous reserve"],
      },
      publicationChecklist: [
        "Besoin de pilotage identifie",
        "Definition sans ambiguite",
        "Formule complete et testee",
        "Unite, cible et sens coherents",
        "Source accessible et reproductible",
        "Frequences realistes",
        "Owner nomme",
        "Justificatifs conserves",
        "Validation hierarchique obtenue",
        "Version et date d'effet enregistrees",
      ],
      controls: [
        { dimension: "Completude", proof: "Valeurs manquantes et justification des absences", frequency: "A chaque collecte" },
        { dimension: "Validite", proof: "Types, unites et listes autorisees", frequency: "A chaque collecte" },
        { dimension: "Coherence", proof: "Rapprochement avec le detail, le budget ou N-1", frequency: "A chaque reporting" },
        { dimension: "Exactitude", proof: "Echantillonnage ou recalcul independant", frequency: "Selon le risque" },
        { dimension: "Actualite", proof: "Date d'extraction et date de validation", frequency: "A chaque reporting" },
      ],
      catalogProfiles: [
        {
          aliases: ["Chiffre d'affaires"],
          id: "KPI-001",
          title: "Chiffre d'affaires",
          definition: "Total des ventes de la periode",
          type: "Financier",
          unit: "Montant (FCFA / XOF)",
          formula: "Volume produit x Prix unitaire HT",
          target: "100",
          collectionFrequency: "Hebdomadaire Mensuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Personne fournissant la donnee",
          responsible: "GNIMAVO Sylvanus",
          respondent: "GNIMAVO Sylvanus",
          respondentFunction: "Controleur de gestion",
          year: "2026",
          hierarchicalValidation: "Non",
          validator: "",
          reference: "Soumission 1 / KPI 1",
          documentStatus: "A valider",
          attention: "Validation hierarchique requise",
        },
        {
          aliases: ["MTTR"],
          id: "KPI-010",
          title: "MTTR",
          definition: "QOS : Assurer l'amelioration de la satisfaction client",
          type: "Satisfaction Client",
          unit: "Minutes",
          formula: "Moyenne de temps de traitement de tous les tickets sur la periode",
          target: "60",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Systeme, fichier",
          responsible: "Responsable support et maintenance",
          respondent: "AGUIAH Leandre",
          respondentFunction: "Directeur des Systemes d'Information",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "KPI COPC",
          reference: "Soumission 2 / KPI 10",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Disponibilite systemes", "Taux de Disponibilite / Accessibilite"],
          id: "KPI-005",
          title: "Taux de Disponibilite / Accessibilite",
          definition: "Assurer la disponibilite de l'infrastructure",
          type: "Productivite",
          unit: "% (Pourcentage)",
          formula: "Nombre de minutes de disponibilite du commutateur x 100 / total des minutes de service ouvert",
          target: "98",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Systeme, fichier et personne",
          responsible: "Responsable Reseau & Systeme",
          respondent: "AGUIAH Leandre",
          respondentFunction: "Directeur des Systemes d'Information",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "KPI COPC",
          reference: "Soumission 2 / KPI 5",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Taux de recouvrement", "Recouvrement", "Recouvrement global"],
          id: "KPI-045",
          title: "Taux de recouvrement",
          definition: "Pourcentage de creances effectivement encaissees par rapport aux creances exigibles",
          type: "Financier",
          unit: "% (Pourcentage)",
          formula: "Somme des encaissements sur la periode / somme des creances exigibles sur la meme periode x 100",
          target: "75",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Fichier finances",
          responsible: "AKUEGNON EDNA-CHARLO",
          respondent: "AKUEGNON EDNA-CHARLO ASSEREOU",
          respondentFunction: "Responsable recouvrement groupe",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "Michele DEGBOE",
          reference: "Soumission 9 / KPI 45",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Taux d'occupation", "TAUX D'OCCUPATION"],
          id: "KPI-053",
          title: "TAUX D'OCCUPATION",
          definition: "Mesure le temps productif par rapport au temps total traite par les ressources WFM",
          type: "Productivite",
          unit: "% (Pourcentage)",
          formula: "Traitement + attente / Traitement + attente + post appel x 100",
          target: "75",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Extractions CX Insights / Hermes / Genesys / Nobelbiz",
          responsible: "ANAIS AHUIASSOU / ERICK AGBA",
          respondent: "ANAIS AHUIASSOU",
          respondentFunction: "Charge planification et reporting",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "JAMES MANGA",
          reference: "Soumission 10 / KPI 53",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Adherence au planning", "ADHERENCE PLANNING"],
          id: "KPI-054",
          title: "ADHERENCE PLANNING",
          definition: "Degre de respect des heures programmees par rapport aux heures planifiees",
          type: "Productivite",
          unit: "% (Pourcentage)",
          formula: "ETP effectif total planifie / besoin x 100",
          target: "90",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Outil WFM et extractions CX Insights / Hermes / Genesys / Nobelbiz",
          responsible: "ANAIS AHUIASSOU / ERICK AGBA",
          respondent: "ANAIS AHUIASSOU",
          respondentFunction: "Charge planification et reporting",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "JAMES MANGA",
          reference: "Soumission 10 / KPI 54",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Taux de service (SL)", "Taux de service client"],
          id: "KPI-061",
          title: "Taux de service client",
          definition: "Capacite du service a satisfaire les demandes des clients internes",
          type: "Satisfaction Client",
          unit: "% (Pourcentage)",
          formula: "Nombre de demandes satisfaites / nombre total de demandes exprimees x 100",
          target: "90",
          collectionFrequency: "Mensuelle",
          reportingFrequency: "Mensuelle",
          dataSource: "Formulaires de demande, tableaux de suivi des demandes, mails",
          responsible: "Responsable Achats et Moyens Generaux",
          respondent: "GANKPA Juste",
          respondentFunction: "Responsable Achats et Moyens Generaux",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "Michele DEGBOE",
          reference: "Soumission 11 / KPI 61",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
      ],
    },

    branchScores: [
      { name: "Cote d'Ivoire", score: 88 },
      { name: "Benin", score: 84 },
      { name: "Cameroun", score: 79 },
      { name: "Congo", score: 73 },
      { name: "Guinee Conakry", score: 69 },
      { name: "Guinee-Bissau", score: 62 },
    ],

    groups: [
      { name: "AAIM", count: 13, validation: "100%", priority: "RAS" },
      { name: "DPB", count: 1, validation: "100%", priority: "RAS" },
      { name: "Hoope Cote d'Ivoire", count: 8, validation: "100%", priority: "RAS" },
      { name: "Hoope Niger", count: 4, validation: "0%", priority: "Validation a completer" },
      { name: "Pole Marketing et Communication", count: 10, validation: "0%", priority: "Validation a completer" },
      { name: "Pole Recouvrement", count: 7, validation: "100%", priority: "RAS" },
      { name: "Direction du Systeme Informatique", count: 10, validation: "100%", priority: "RAS" },
      { name: "Pole Moyens Generaux", count: 6, validation: "100%", priority: "RAS" },
      { name: "Pole Voix du Client & EPC", count: 7, validation: "100%", priority: "RAS" },
      { name: "Direction Finance et Comptabilite", count: 3, validation: "0%", priority: "Validation a completer" },
      { name: "Pole WFM", count: 5, validation: "100%", priority: "RAS" },
    ],

    methodologyControls: [
      {
        dimension: "Completude",
        question: "Toutes les donnees attendues sont presentes.",
        proof: "Valeurs manquantes et justification des absences",
        frequency: "A chaque collecte",
      },
      {
        dimension: "Validite",
        question: "Les formats, unites et domaines de valeurs sont respectes.",
        proof: "Types, bornes et listes autorisees",
        frequency: "A chaque collecte",
      },
      {
        dimension: "Coherence",
        question: "Les agregats et les evolutions sont plausibles.",
        proof: "Rapprochement avec le detail, le budget ou N-1",
        frequency: "A chaque reporting",
      },
      {
        dimension: "Exactitude",
        question: "La valeur reflete fidelement la source.",
        proof: "Echantillonnage ou recalcul independant",
        frequency: "Selon le risque",
      },
      {
        dimension: "Actualite",
        question: "La valeur est disponible dans le delai.",
        proof: "Date d'extraction et date de validation",
        frequency: "A chaque reporting",
      },
    ],

    collectionForms: [
      {
        code: "BPO",
        title: "Fiche BPO - Direction des operations",
        cadence: "Journaliere / Horaire",
        sections: ["Parametres de campagne", "RA Top 20", "Donnees quantitatives journalieres"],
      },
      {
        code: "DFC",
        title: "Fiche DFC - Finance & Controle de gestion",
        cadence: "Journaliere / Mensuelle",
        sections: ["Parametres financiers previsionnels", "Donnees financieres journalieres"],
      },
      {
        code: "WFM",
        title: "Fiche WFM - Workforce Management",
        cadence: "Journaliere",
        sections: ["Objectifs de planification", "Donnees quantitatives WFM"],
      },
      {
        code: "DSI",
        title: "Fiche DSI - Systeme d'information",
        cadence: "Journaliere",
        sections: ["Parametres infrastructure", "Incidents techniques et disponibilite"],
      },
      {
        code: "DCH",
        title: "Fiche DCH - Capital humain",
        cadence: "Journaliere / Hebdomadaire",
        sections: ["Grille remunerations", "CRCD titulaire", "CRCD stagiaire", "CRCD prestataire"],
      },
      {
        code: "EPC",
        title: "Fiche EPC - Evaluation & pilotage qualite",
        cadence: "Hebdomadaire",
        sections: ["Parametres qualite", "Resultats qualite hebdomadaires"],
      },
      {
        code: "DCM",
        title: "Fiche DCM - Direction des comptes",
        cadence: "Hebdomadaire",
        sections: ["Parametres contractuels", "Conformite et obligations contractuelles"],
      },
    ],

    koboSubmissions: [
      { form: "KBO-BPO-JOUR-01", branch: "Cote d'Ivoire", kpi: "Taux de service (SL)", collector: "A. Traore", status: "Valide", className: "green" },
      { form: "KBO-WFM-JOUR-02", branch: "Congo", kpi: "Taux d'occupation", collector: "M. Nkoua", status: "En retard", className: "gray" },
      { form: "KBO-FIN-MENS-01", branch: "Benin", kpi: "Ratio MS/CA", collector: "S. Houngue", status: "Erreur mapping", className: "red" },
      { form: "KBO-RH-HEBD-01", branch: "Guinee Conakry", kpi: "Taux d'absenteisme", collector: "I. Diallo", status: "A valider", className: "amber" },
      { form: "KBO-QUAL-MENS-01", branch: "Cameroun", kpi: "Quality Score", collector: "L. Mbarga", status: "Valide", className: "green" },
    ],

    koboPipeline: [
      { title: "Reception Kobo", detail: "Webhook ou synchronisation planifiee depuis KoboToolbox.", count: "1 285", status: "Actif", className: "green" },
      { title: "Zone de controle", detail: "Doublons, formats, pieces jointes et champs obligatoires.", count: "17", status: "A traiter", className: "amber" },
      { title: "Mapping KPI", detail: "Rattachement formulaire, pole, filiale, periode et code KPI.", count: "44", status: "Regles", className: "green" },
      { title: "Calcul PMS", detail: "Application des formules et seuils RAG du catalogue.", count: "74", status: "Pret", className: "green" },
      { title: "Publication", detail: "Mise a jour tableau de bord, alertes et rapports par pole.", count: "7", status: "Cycles", className: "green" },
    ],

    validationQueue: [
      { id: "VAL-1024", form: "KBO-FIN-MENS-01", pole: "DFC", issue: "Ratio MS/CA hors seuil et piece justificative manquante", owner: "Analyste BI", status: "Critique", className: "red" },
      { id: "VAL-1025", form: "KBO-WFM-JOUR-02", pole: "WFM", issue: "Soumission Congo en retard de 24h", owner: "Responsable WFM", status: "Relance", className: "gray" },
      { id: "VAL-1026", form: "KBO-RH-HEBD-01", pole: "DCH", issue: "Ecart absenteisme a commenter avant rapport hebdomadaire", owner: "DRH", status: "A valider", className: "amber" },
      { id: "VAL-1027", form: "KBO-BPO-JOUR-01", pole: "BPO", issue: "Taux abandon rouge, plan d'action requis", owner: "Directeur operations", status: "Plan requis", className: "red" },
    ],

    formulaDictionary: [
      { id: "01", direction: "BPO", name: "Taux de service (SL)", category: "Qualite service", frequency: "Horaire", target: ">= 80-90%", source: "FORMULE" },
      { id: "02", direction: "BPO", name: "Taux de decrochage", category: "Qualite service", frequency: "Horaire", target: ">= 95%", source: "FORMULE" },
      { id: "03", direction: "BPO", name: "Taux d'abandon", category: "Qualite service", frequency: "Horaire", target: "<= 5%", source: "FORMULE" },
      { id: "04", direction: "BPO", name: "DMT - Duree Moyenne de Traitement", category: "Productivite", frequency: "Journalier", target: "Selon contrat", source: "FORMULE" },
      { id: "05", direction: "BPO", name: "Taux de facturation", category: "Finance", frequency: "Journalier", target: ">= 85-95%", source: "FORMULE" },
      { id: "06", direction: "BPO", name: "CA de l'heure", category: "Finance horaire", frequency: "Horaire / Jour", target: "Selon objectif", source: "FORMULE" },
      { id: "07", direction: "BPO", name: "CA par agent par jour", category: "Finance", frequency: "Journalier", target: "Selon objectif", source: "FORMULE" },
      { id: "08", direction: "BPO", name: "Performance horaire par agent", category: "Productivite", frequency: "Journalier", target: "Selon objectif", source: "FORMULE" },
      { id: "09", direction: "BPO", name: "Taux d'atteinte CA", category: "Finance", frequency: "Horaire / Jour", target: ">= 100%", source: "FORMULE" },
      { id: "13", direction: "WFM", name: "Taux d'occupation / Occupancy", category: "Planification", frequency: "Horaire", target: "75-85%", source: "FORMULE" },
      { id: "14", direction: "WFM", name: "Adherence au planning", category: "Planification", frequency: "Journalier", target: ">= 85-90%", source: "FORMULE" },
      { id: "15", direction: "WFM", name: "Shrinkage - Coefficient d'absenteisme", category: "Planification", frequency: "Journalier", target: "<= 20%", source: "FORMULE" },
      { id: "16", direction: "WFM", name: "Taux de presence vs planning", category: "Planification", frequency: "Journalier", target: ">= 95%", source: "FORMULE" },
      { id: "19", direction: "DCH", name: "Taux d'absenteisme", category: "RH", frequency: "Journalier", target: "<= 5%", source: "FORMULE" },
      { id: "20", direction: "DCH", name: "Taux de rotation / Turnover", category: "RH", frequency: "Mensuel", target: "<= cible", source: "FORMULE" },
      { id: "31", direction: "DSI", name: "Disponibilite des systemes", category: "IT", frequency: "Journalier", target: ">= 99.5%", source: "FORMULE" },
      { id: "32", direction: "DSI", name: "MTTR", category: "IT", frequency: "Hebdomadaire", target: "<= 4h", source: "FORMULE" },
      { id: "40", direction: "CONSOLIDE", name: "Indice de performance consolide", category: "Pilotage", frequency: "Mensuel", target: ">= 80 pts", source: "FORMULE" },
    ],

    alerts: [
      {
        title: "Ratio MS/CA superieur au seuil",
        scope: "DFC - Cote d'Ivoire",
        detail: "65% sur la periode courante, plan de redressement requis sous 3 jours.",
        level: "red",
      },
      {
        title: "Taux d'appels facturables < 80%",
        scope: "BU BPO - Cameroun",
        detail: "Trois tranches horaires consecutives sous objectif, escalade Qualite + Supervision.",
        level: "red",
      },
      {
        title: "Absence de soumission J+1",
        scope: "WFM - Congo",
        detail: "Le formulaire Kobo journalier n'a pas ete synchronise depuis 24h.",
        level: "gray",
      },
      {
        title: "NPS en recul",
        scope: "Voix du Client - Groupe",
        detail: "Baisse de 7 points vs trimestre precedent, analyse IA recommandee.",
        level: "amber",
      },
    ],

    actionPlans: [
      { title: "Reduire le ratio MS/CA", owner: "DFC + DCH", due: "30/07/2026", progress: 45, detail: "Revue staffing indirect, gel remplacements non critiques et suivi hebdomadaire." },
      { title: "Augmenter les appels facturables", owner: "BU BPO + Qualite", due: "12/07/2026", progress: 68, detail: "Correction codification motifs, coaching short calls et controle qualite quotidien." },
      { title: "Rattraper collecte WFM Congo", owner: "WFM Congo", due: "08/07/2026", progress: 25, detail: "Relance collecteurs, verification smartphones offline et re-synchronisation Kobo." },
    ],

    reports: [
      { title: "Rapport COMEX Word", detail: "Narratif executif, tableaux KPI, alertes et plans d'action.", format: "DOCX" },
      { title: "Slides Performance Groupe", detail: "Synthese IPG, RAG, tendances et benchmark filiales.", format: "PPTX" },
      { title: "Base KPI Consolidee", detail: "Donnees brutes, calculs, controles qualite et mapping Kobo.", format: "XLSX" },
      { title: "Archive mensuelle", detail: "Version figee pour diffusion et historique audit.", format: "PDF" },
      { title: "Email hebdomadaire", detail: "Resume HTML automatique des KPIs et alertes prioritaires.", format: "EMAIL" },
      { title: "Rapport pertes CA", detail: "Pertes par source, tranche horaire, filiale et responsable.", format: "PPTX" },
    ],

    reporting: {
      defaultPole: "BPO",
      defaultCycle: "Hebdomadaire",
      cycles: [
        { value: "Hebdomadaire", deadline: "Lundi 08h00", scope: "Suivi operationnel, alertes et actions court terme" },
        { value: "Mensuel", deadline: "05 du mois M+1", scope: "Rapport direction, COMEX et consolidation filiale" },
        { value: "Trimestriel", deadline: "10 du mois suivant", scope: "Analyse strategique, benchmark et trajectoire" },
        { value: "Semestriel", deadline: "15 du 7e / 1er mois", scope: "Revue maturite et amelioration continue" },
        { value: "Annuel", deadline: "31 janvier N+1", scope: "Bilan groupe, actionnaires et audit" },
      ],
      poles: [
        { id: "DFC", category: "Direction Generale", name: "Direction Finance & Comptabilite", owner: "Directeur financier", kpiCount: 3, score: 66, rag: "red", quality: 76, lastReport: "Juin 2026", status: "Plan requis", lateSubmissions: 3, actionCount: 5, readiness: 61 },
        { id: "PSMQ", category: "Direction Generale", name: "Pole Systeme de Management de la Qualite", owner: "Responsable qualite", kpiCount: 6, score: 82, rag: "green", quality: 91, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 88 },
        { id: "WFM", category: "Direction Generale", name: "Pole WFM", owner: "Responsable WFM", kpiCount: 5, score: 84, rag: "green", quality: 89, lastReport: "S27 2026", status: "Brouillon", lateSubmissions: 2, actionCount: 2, readiness: 78 },
        { id: "DRIVE", category: "Direction Generale", name: "Pole Projet DRIVE", owner: "Chef projet DRIVE", kpiCount: 5, score: 79, rag: "amber", quality: 87, lastReport: "Juin 2026", status: "En cours", lateSubmissions: 1, actionCount: 3, readiness: 73 },
        { id: "COM", category: "DGA Business & Expansion", name: "Pole Commercial", owner: "Responsable commercial", kpiCount: 4, score: 72, rag: "amber", quality: 83, lastReport: "Juin 2026", status: "A completer", lateSubmissions: 1, actionCount: 3, readiness: 70 },
        { id: "GDC", category: "DGA Business & Expansion", name: "Pole Gestionnaire de Compte", owner: "Responsable comptes", kpiCount: 4, score: 75, rag: "amber", quality: 84, lastReport: "Juin 2026", status: "A valider", lateSubmissions: 1, actionCount: 2, readiness: 76 },
        { id: "REC", category: "DGA Business & Expansion", name: "Pole Recouvrement", owner: "Responsable recouvrement", kpiCount: 7, score: 69, rag: "red", quality: 80, lastReport: "Juin 2026", status: "Plan requis", lateSubmissions: 2, actionCount: 5, readiness: 64 },
        { id: "BRD", category: "DGA Business & Expansion", name: "BU Retail & Distribution", owner: "Directeur retail", kpiCount: 8, score: 77, rag: "amber", quality: 86, lastReport: "Juin 2026", status: "En cours", lateSubmissions: 1, actionCount: 3, readiness: 75, note: "Hoope CI et Niger" },
        { id: "BPO", category: "DGA Business & Expansion", name: "BU BPO", owner: "Directeur des operations", kpiCount: 12, score: 78, rag: "amber", quality: 92, lastReport: "S27 2026", status: "A valider", lateSubmissions: 1, actionCount: 4, readiness: 86 },
        { id: "BID", category: "DGA Business & Expansion", name: "BU Innovation & Developpement", owner: "Directeur innovation", kpiCount: 8, score: 80, rag: "green", quality: 88, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 85, note: "AAIM, DPB, SCI" },
        { id: "PAC", category: "DGA Support & Performance", name: "Pole Performance & Amelioration Continue", owner: "Responsable performance", kpiCount: 6, score: 83, rag: "green", quality: 90, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 89 },
        { id: "EPC", category: "DGA Support & Performance", name: "Pole Voix du Client & EPC", owner: "Responsable EPC", kpiCount: 7, score: 81, rag: "green", quality: 90, lastReport: "T2 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 91 },
        { id: "DSI", category: "DGA Support & Performance", name: "Direction Systeme Informatique", owner: "DSI", kpiCount: 10, score: 88, rag: "green", quality: 94, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 1, readiness: 96 },
        { id: "DCH", category: "DGA Support & Performance", name: "Direction Capital Humain", owner: "DRH", kpiCount: 7, score: 73, rag: "amber", quality: 85, lastReport: "S27 2026", status: "En cours", lateSubmissions: 1, actionCount: 3, readiness: 74 },
        { id: "PMG", category: "DGA Support & Performance", name: "Pole Moyens Generaux", owner: "Responsable moyens generaux", kpiCount: 6, score: 76, rag: "amber", quality: 84, lastReport: "Juin 2026", status: "A valider", lateSubmissions: 1, actionCount: 2, readiness: 77 },
      ],
      kpisByPole: {
        BPO: [
          { name: "Taux de service (SL)", value: "78%", target: ">= 80-90%", trend: "-2 pts", status: "amber", source: "KBO-BPO-JOUR-01" },
          { name: "Taux d'abandon", value: "6.8%", target: "<= 5%", trend: "+1.1 pt", status: "red", source: "KBO-BPO-JOUR-01" },
          { name: "Taux de facturation", value: "87%", target: ">= 85-95%", trend: "+4 pts", status: "green", source: "KBO-HORAIRE-JOUR-03" },
          { name: "CA de l'heure", value: "1.9M FCFA", target: "Selon objectif", trend: "-8%", status: "amber", source: "KBO-HORAIRE-JOUR-03" },
        ],
        WFM: [
          { name: "Taux d'occupation", value: "82%", target: "75-85%", trend: "+3 pts", status: "green", source: "KBO-WFM-JOUR-02" },
          { name: "Adherence au planning", value: "88%", target: ">= 85-90%", trend: "+1 pt", status: "green", source: "KBO-WFM-JOUR-02" },
          { name: "Shrinkage", value: "18%", target: "<= 20%", trend: "-2 pts", status: "green", source: "KBO-WFM-JOUR-02" },
        ],
        DFC: [
          { name: "Ratio MS/CA", value: "65%", target: "<= 45%", trend: "+7 pts", status: "red", source: "KBO-FIN-MENS-01" },
          { name: "Chiffre d'affaires", value: "412M FCFA", target: "Objectif mensuel", trend: "-9%", status: "amber", source: "KBO-FIN-MENS-01" },
          { name: "Recouvrement", value: "73%", target: ">= 85%", trend: "-4 pts", status: "red", source: "KBO-FIN-MENS-01" },
        ],
        PSMQ: [
          { name: "Taux conformite processus", value: "91%", target: ">= 90%", trend: "+3 pts", status: "green", source: "KBO-QUAL-PROC-01" },
          { name: "Actions correctives cloturees", value: "84%", target: ">= 85%", trend: "-1 pt", status: "amber", source: "KBO-QUAL-PROC-01" },
          { name: "Audits internes realises", value: "96%", target: ">= 95%", trend: "+4 pts", status: "green", source: "KBO-QUAL-AUDIT-01" },
        ],
        DRIVE: [
          { name: "Jalons projet tenus", value: "78%", target: ">= 85%", trend: "-5 pts", status: "amber", source: "KBO-DRIVE-MENS-01" },
          { name: "Livrables valides", value: "82%", target: ">= 80%", trend: "+6 pts", status: "green", source: "KBO-DRIVE-MENS-01" },
          { name: "Risques ouverts", value: "6", target: "<= 3", trend: "+2", status: "red", source: "KBO-DRIVE-RISK-01" },
        ],
        DCH: [
          { name: "Taux d'absenteisme", value: "5.8%", target: "<= 5%", trend: "+0.6 pt", status: "amber", source: "KBO-RH-HEBD-01" },
          { name: "Taux de presence", value: "94%", target: ">= 95%", trend: "-1 pt", status: "amber", source: "KBO-RH-HEBD-01" },
          { name: "Turnover mensuel", value: "3.9%", target: "<= cible", trend: "stable", status: "green", source: "KBO-RH-HEBD-01" },
        ],
        DSI: [
          { name: "Disponibilite systemes", value: "99.7%", target: ">= 99.5%", trend: "+0.1 pt", status: "green", source: "KBO-DSI-JOUR-01" },
          { name: "MTTR", value: "3h20", target: "<= 4h", trend: "-35 min", status: "green", source: "KBO-DSI-JOUR-01" },
          { name: "Incidents securite", value: "2", target: "0 critique", trend: "-1", status: "amber", source: "KBO-DSI-JOUR-01" },
        ],
        EPC: [
          { name: "Quality Score", value: "86%", target: ">= 85%", trend: "+2 pts", status: "green", source: "KBO-QUAL-MENS-01" },
          { name: "CSAT", value: "82%", target: ">= 85%", trend: "-3 pts", status: "amber", source: "KBO-QUAL-MENS-01" },
          { name: "Reclamations J+1", value: "74%", target: ">= 70%", trend: "+5 pts", status: "green", source: "KBO-QUAL-MENS-01" },
        ],
        DCM: [
          { name: "Taux de conversion", value: "17%", target: ">= 20%", trend: "-2 pts", status: "amber", source: "KBO-DCM-HEBD-01" },
          { name: "Pipeline commercial", value: "81%", target: ">= 100%", trend: "+6 pts", status: "amber", source: "KBO-DCM-HEBD-01" },
          { name: "Recouvrement global", value: "79%", target: ">= 85%", trend: "-1 pt", status: "amber", source: "KBO-DCM-HEBD-01" },
        ],
        COM: [
          { name: "Taux de conversion", value: "17%", target: ">= 20%", trend: "-2 pts", status: "amber", source: "KBO-COM-HEBD-01" },
          { name: "Nouveaux contrats signes", value: "11", target: "15", trend: "+2", status: "amber", source: "KBO-COM-HEBD-01" },
          { name: "Pipeline qualifie", value: "81%", target: ">= 90%", trend: "+6 pts", status: "amber", source: "KBO-COM-PIPE-01" },
        ],
        GDC: [
          { name: "Taux renouvellement comptes", value: "88%", target: ">= 85%", trend: "+3 pts", status: "green", source: "KBO-GDC-MENS-01" },
          { name: "Satisfaction comptes cles", value: "82%", target: ">= 85%", trend: "-2 pts", status: "amber", source: "KBO-GDC-MENS-01" },
          { name: "Plans comptes a jour", value: "76%", target: ">= 80%", trend: "+4 pts", status: "amber", source: "KBO-GDC-PLAN-01" },
        ],
        REC: [
          { name: "Taux de recouvrement", value: "73%", target: ">= 85%", trend: "-4 pts", status: "red", source: "KBO-REC-MENS-01" },
          { name: "Creances > 90 jours", value: "18%", target: "<= 10%", trend: "+3 pts", status: "red", source: "KBO-REC-MENS-01" },
          { name: "Dossiers relances", value: "91%", target: ">= 90%", trend: "+5 pts", status: "green", source: "KBO-REC-HEBD-01" },
        ],
        BRD: [
          { name: "CA retail", value: "94%", target: ">= 100%", trend: "+4 pts", status: "amber", source: "KBO-BRD-MENS-01" },
          { name: "Disponibilite points de vente", value: "97%", target: ">= 95%", trend: "+1 pt", status: "green", source: "KBO-BRD-JOUR-01" },
          { name: "Ruptures critiques", value: "5", target: "0 critique", trend: "-2", status: "amber", source: "KBO-BRD-STOCK-01" },
        ],
        BID: [
          { name: "Taux avancement projets", value: "86%", target: ">= 80%", trend: "+7 pts", status: "green", source: "KBO-BID-MENS-01" },
          { name: "Projets en retard", value: "2", target: "<= 2", trend: "stable", status: "green", source: "KBO-BID-MENS-01" },
          { name: "ROI initiatives", value: "71%", target: ">= 75%", trend: "+3 pts", status: "amber", source: "KBO-BID-ROI-01" },
        ],
        PAC: [
          { name: "Taux plans actions clotures", value: "89%", target: ">= 85%", trend: "+6 pts", status: "green", source: "KBO-PAC-MENS-01" },
          { name: "Gains productivite", value: "7.5%", target: ">= 5%", trend: "+1.2 pt", status: "green", source: "KBO-PAC-MENS-01" },
          { name: "Chantiers en retard", value: "3", target: "<= 2", trend: "+1", status: "amber", source: "KBO-PAC-HEBD-01" },
        ],
        PMG: [
          { name: "Disponibilite moyens", value: "92%", target: ">= 95%", trend: "-2 pts", status: "amber", source: "KBO-PMG-JOUR-01" },
          { name: "Delai traitement demandes", value: "3.8j", target: "<= 3j", trend: "+0.4j", status: "amber", source: "KBO-PMG-HEBD-01" },
          { name: "Conformite inventaire", value: "96%", target: ">= 95%", trend: "+2 pts", status: "green", source: "KBO-PMG-MENS-01" },
        ],
      },
      workflow: [
        { step: "1. Collecte Kobo", detail: "Soumissions terrain synchronisees et controlees." },
        { step: "2. Consolidation KPI", detail: "Calculs, RAG, tendances et donnees manquantes." },
        { step: "3. Commentaire pole", detail: "Causes, faits marquants et plan d'action SMART." },
        { step: "4. Validation N+1", detail: "Visa direction / DGA avant diffusion." },
        { step: "5. Export & diffusion", detail: "Word, PDF, PowerPoint, Excel ou email planifie." },
      ],
      checklist: [
        { key: "Donnees Kobo synchronisees", owner: "Responsable collecte" },
        { key: "Controle completude et validite", owner: "Analyste BI" },
        { key: "Commentaires sur KPI orange/rouge", owner: "Responsable pole" },
        { key: "Plan d'action SMART rattache", owner: "Directeur fonctionnel" },
        { key: "Validation N+1 avant diffusion", owner: "DGA / DG" },
      ],
      calendar: [
        { pole: "BPO", cycle: "Hebdomadaire", period: "S28 2026", due: "13/07/2026 08:00", status: "A valider", owner: "Directeur des operations" },
        { pole: "WFM", cycle: "Hebdomadaire", period: "S28 2026", due: "13/07/2026 08:00", status: "Brouillon", owner: "Responsable WFM" },
        { pole: "DFC", cycle: "Mensuel", period: "Juin 2026", due: "05/07/2026 18:00", status: "Plan requis", owner: "Directeur financier" },
        { pole: "DCH", cycle: "Hebdomadaire", period: "S28 2026", due: "13/07/2026 08:00", status: "En cours", owner: "DRH" },
        { pole: "DSI", cycle: "Mensuel", period: "Juin 2026", due: "05/07/2026 18:00", status: "Valide", owner: "DSI" },
        { pole: "EPC", cycle: "Trimestriel", period: "T2 2026", due: "10/07/2026 18:00", status: "Valide", owner: "Responsable EPC" },
        { pole: "DCM", cycle: "Mensuel", period: "Juin 2026", due: "05/07/2026 18:00", status: "A completer", owner: "Directeur commercial" },
      ],
      distribution: [
        { audience: "Responsable pole", channel: "In-app + email", timing: "Avant validation", status: "Actif", className: "green" },
        { audience: "Direction fonctionnelle", channel: "PDF signe", timing: "Apres validation N+1", status: "A valider", className: "amber" },
        { audience: "COMEX / DG", channel: "Word COMEX + slides", timing: "Selon calendrier", status: "Planifie", className: "green" },
        { audience: "Archive audit", channel: "PDF + Excel donnees", timing: "A chaque cloture", status: "Actif", className: "green" },
      ],
      history: [
        { id: "RPT-2026-S27-BPO", pole: "BPO", cycle: "Hebdomadaire", period: "S27 2026", format: "Word COMEX", status: "Valide", generatedAt: "06/07/2026 08:14" },
        { id: "RPT-2026-06-DFC", pole: "DFC", cycle: "Mensuel", period: "Juin 2026", format: "PDF signe", status: "Plan requis", generatedAt: "05/07/2026 17:22" },
        { id: "RPT-2026-T2-EPC", pole: "EPC", cycle: "Trimestriel", period: "T2 2026", format: "PowerPoint synthese", status: "Valide", generatedAt: "04/07/2026 11:05" },
      ],
    },

    roles: [
      ["Super Administrateur", "Groupe", "Oui", "Oui", "Total"],
      ["Administrateur Categorie", "Categorie", "Oui", "Oui", "Partiel"],
      ["Directeur Fonctionnel", "Direction", "Oui", "N+1", "Non"],
      ["Responsable Pole", "Pole", "Oui", "Non", "Non"],
      ["Analyste BI", "Groupe", "Non", "Non", "Exports"],
      ["COMEX / DG", "Groupe", "Non", "Non", "Lecture"],
      ["Auditeur externe", "Limite", "Non", "Non", "Temporaire"],
    ],

    auditTrail: [
      "08:42 - Sync Kobo KBO-BPO-JOUR-01 integree",
      "08:33 - Seuil Ratio MS/CA modifie par Admin",
      "08:12 - Plan d'action BPO valide par DGA",
      "07:58 - Rejet doublon formulaire WFM Congo",
    ],
  };

  window.PMS_DATA = data;
})();
