(function () {
  const data = {
    sourceFiles: [
      {
        name: "Catalogue_et_Guide_methodologique_KPI_Palladium_Africa_2026.xlsx",
        role: "Catalogue KPI et guide methodologique",
      },
      {
        name: "GMC_FICHE_COLLECTE_V2.xlsx",
        role: "Fiches KoboCollect et dictionnaire des formules",
      },
      {
        name: "CDC_PMS_GMC_Group_2026.docx",
        role: "Cahier des charges PMS",
      },
    ],

    catalogSummary: {
      kpiCount: 74,
      formulaCount: 44,
      groupCount: 11,
      collectionDomains: 7,
      extractionDate: "24 juin 2026",
      categories: [
        { name: "DGA Business & Expansion", count: 43 },
        { name: "DGA Support & Performance", count: 23 },
        { name: "Direction Generale", count: 8 },
      ],
      frequencies: [
        { name: "Hebdo / Mensuel / Trimestriel / Annuel", count: 48 },
        { name: "Hebdomadaire / Mensuelle", count: 14 },
        { name: "Mensuelle", count: 6 },
        { name: "Mensuelle / Trimestrielle / Annuelle", count: 4 },
        { name: "Hebdomadaire", count: 2 },
      ],
    },

    objectiveKoboTemplate: {
      sourceFile: "Catalogue_et_Guide_methodologique_KPI_Palladium_Africa_2026.xlsx",
      catalogSheet: "Catalogue KPI",
      modelSheet: "Fiche KPI modele",
      catalogKpiCount: 74,
      sourceWorkbookProfile: {
        fileName: "Copie de Catalogu.xlsx",
        sheetName: "Catalogue KPI",
        kpiCount: 74,
        groupCount: 11,
        categoryCount: 3,
        formulaMissing: 0,
        targetMissing: 13,
        documentedCount: 57,
      },
      collectionWorkbookProfile: {
        fileName: "GMC_FICHE_COLLECTE_V2.xlsx",
        formulaSheet: "FORMULE",
        formulaCount: 44,
        collectionSheets: 7,
        sheets: [
          {
            code: "BPO",
            title: "BPO - Direction des operations",
            cadence: "Horaire / Journalier",
            expectedFields: ["Pays", "Portefeuille / client", "Type d'activite", "SLA qualite", "DMT", "Appels recus", "Appels traites", "Appels facturables", "Agents presents", "Appels abandonnes"],
          },
          {
            code: "DFC",
            title: "DFC - Finance & controle de gestion",
            cadence: "Quotidien / Mensuel",
            expectedFields: ["CA previsionnel mensuel", "MS/CA previsionnel", "CA/heure previsionnel", "Objectif CA journalier", "Nb jours ouvres", "Masse salariale directe"],
          },
          {
            code: "WFM",
            title: "WFM - Workforce management",
            cadence: "Horaire / Journalier",
            expectedFields: ["Heures planifiees", "Heures realisees", "Agents planifies", "Agents presents", "Temps communication", "Temps ACW", "Temps presence", "Absents", "Retards", "Heures supplementaires"],
          },
          {
            code: "DSI",
            title: "DSI - Systemes d'information",
            cadence: "Journalier / Mensuel",
            expectedFields: ["Disponibilite systeme", "Incidents P1", "Incidents P2", "Duree indisponibilite", "Tickets ouverts", "Tickets resolus", "Postes HS", "Bande passante", "Licences actives"],
          },
          {
            code: "DCH",
            title: "DCH - Capital humain",
            cadence: "Journalier / Mensuel",
            expectedFields: ["Effectif theorique", "Effectif present", "Absences justifiees", "Conges", "Absences non justifiees", "Retards", "Entrees", "Sorties volontaires", "Sorties involontaires"],
          },
          {
            code: "EPC",
            title: "Pole EPC - Evaluation & pilotage qualite",
            cadence: "Hebdomadaire",
            expectedFields: ["Evaluations realisees", "Evaluations appels entrants", "Evaluations appels sortants", "Interactions digitales", "ECC", "ECA", "ECCo", "ENC", "Defaut global", "Escalade", "Agents evalues", "Coaching realises"],
          },
          {
            code: "DCM",
            title: "DCM - Direction des comptes",
            cadence: "Hebdomadaire / Mensuel",
            expectedFields: ["Obligations MCB conformes", "Obligations MCB non conformes", "Obligations DO conformes", "Obligations DO non conformes", "Malus declenches", "Montant malus", "SLA MCB respectes", "SLA DO respectes", "Contrats en renouvellement"],
          },
        ],
      },
      requiredFields: [
        { key: "id_kpi", label: "ID KPI", source: "ID KPI", block: "Identification" },
        { key: "pays_filiale", label: "Pays / Filiale", source: "Pays / Filiale", block: "Rattachement" },
        { key: "categorie_organisationnelle", label: "Categorie organisationnelle", source: "Categorie organisationnelle", block: "Rattachement" },
        { key: "entite_direction", label: "Entite / Direction", source: "Entite / Direction", block: "Rattachement" },
        { key: "sous_entite_pole_filiale", label: "Sous-entite / Pole / Filiale", source: "Sous-entite / Pole / Filiale", block: "Rattachement" },
        { key: "groupe_de_rattachement", label: "Groupe de rattachement", source: "Groupe de rattachement", block: "Rattachement" },
        { key: "chemin_organisationnel", label: "Chemin organisationnel", source: "Chemin organisationnel", block: "Rattachement" },
        { key: "intitule_du_kpi", label: "Intitule du KPI", source: "Intitule du KPI", block: "Identification" },
        { key: "description_definition", label: "Description / Definition", source: "Description / Definition", block: "Definition" },
        { key: "type_de_kpi", label: "Type de KPI", source: "Type de KPI", block: "Definition" },
        { key: "unite_de_mesure", label: "Unite de mesure", source: "Unite de mesure", block: "Calcul" },
        { key: "formule_de_calcul", label: "Formule de calcul", source: "Formule de calcul", block: "Calcul" },
        { key: "valeur_cible", label: "Valeur cible", source: "Valeur cible", block: "Calcul" },
        { key: "frequence_de_collecte", label: "Frequence de collecte", source: "Frequence de collecte", block: "Donnees" },
        { key: "periodicite_du_reporting", label: "Periodicite du reporting", source: "Periodicite du reporting", block: "Donnees" },
        { key: "source_de_la_donnee", label: "Source de la donnee", source: "Source de la donnee", block: "Donnees" },
        { key: "responsable_du_kpi", label: "Responsable du KPI", source: "Responsable du KPI", block: "Responsabilite" },
        { key: "repondant", label: "Repondant", source: "Repondant", block: "Responsabilite" },
        { key: "fonction_du_repondant", label: "Fonction du repondant", source: "Fonction du repondant", block: "Responsabilite" },
        { key: "annee", label: "Annee", source: "Annee", block: "Periode" },
        { key: "validation_hierarchique", label: "Validation hierarchique", source: "Validation hierarchique", block: "Tracabilite" },
        { key: "validateur", label: "Validateur", source: "Validateur", block: "Tracabilite" },
        { key: "commentaires", label: "Commentaires", source: "Commentaires", block: "Tracabilite" },
        { key: "date_de_soumission", label: "Date de soumission", source: "Date de soumission", block: "Tracabilite" },
        { key: "reference_source", label: "Reference source", source: "Reference source", block: "Tracabilite" },
        { key: "statut_documentaire", label: "Statut documentaire", source: "Statut documentaire", block: "Tracabilite" },
        { key: "points_d_attention", label: "Points d'attention", source: "Points d'attention", block: "Tracabilite" },
      ],
      calculationFields: [
        { key: "pole_id", label: "Pole concerne", source: "Pole responsable de la donnee", block: "Rattachement" },
        { key: "id_kpi", label: "KPI a calculer", source: "Lien avec le formulaire KPI", block: "Rattachement" },
        { key: "periode_reporting", label: "Periode de reporting", source: "Mois, semaine ou trimestre", block: "Temps" },
        { key: "element_id", label: "Element de calcul", source: "Variable utilisee dans la formule", block: "Calcul" },
        { key: "valeur_element", label: "Valeur collectee", source: "Numerateur, denominateur ou valeur brute", block: "Calcul" },
        { key: "unite_mesure", label: "Unite de la valeur", source: "Pourcentage, montant, nombre, minutes", block: "Calcul" },
        { key: "filiale", label: "Filiale / pays", source: "Perimetre de consolidation", block: "Perimetre" },
        { key: "date_collecte", label: "Date de collecte", source: "Horodatage metier", block: "Tracabilite" },
        { key: "source_donnee", label: "Source de la donnee", source: "Systeme, fichier ou responsable", block: "Tracabilite" },
        { key: "validation_hierarchique", label: "Validation", source: "Controle avant calcul PMS", block: "Tracabilite" },
      ],
      koboLogicSteps: [
        "Formulaire 1 : declare les KPI, pays / filiales, poles, objectifs et formules de calcul.",
        "Formulaire 2 : collecte les elements bruts necessaires a ces formules.",
        "La plateforme rapproche les deux formulaires par pays / filiale, pole, KPI et periode.",
        "Le PMS calcule ensuite les valeurs KPI et alimente les tableaux de bord par pole.",
      ],
      referentials: {
        types: ["Financier", "Commercial", "Productivite", "Qualite", "Satisfaction Client", "Operationnel", "Strategique"],
        units: ["% (Pourcentage)", "Nombre / Quantite", "Montant (FCFA / XOF)", "Minutes", "Jours", "Autre"],
        frequencies: ["Hebdomadaire", "Mensuelle", "Trimestrielle", "Semestrielle", "Annuelle"],
        statuses: ["Brouillon", "A preciser", "A valider", "Actif", "Suspendu", "Archive"],
        validations: ["Oui", "Non", "Sous reserve"],
      },
      publicationChecklist: [
        "Besoin de pilotage identifie",
        "Definition sans ambiguite",
        "Formule complete et testee",
        "Unite, cible et sens coherents",
        "Source accessible et reproductible",
        "Frequences realistes",
        "Owner nomme",
        "Justificatifs conserves",
        "Validation hierarchique obtenue",
        "Version et date d'effet enregistrees",
      ],
      controls: [
        { dimension: "Completude", proof: "Valeurs manquantes et justification des absences", frequency: "A chaque collecte" },
        { dimension: "Validite", proof: "Types, unites et listes autorisees", frequency: "A chaque collecte" },
        { dimension: "Coherence", proof: "Rapprochement avec le detail, le budget ou N-1", frequency: "A chaque reporting" },
        { dimension: "Exactitude", proof: "Echantillonnage ou recalcul independant", frequency: "Selon le risque" },
        { dimension: "Actualite", proof: "Date d'extraction et date de validation", frequency: "A chaque reporting" },
      ],
      catalogProfiles: [
        {
          aliases: ["Chiffre d'affaires"],
          id: "KPI-001",
          title: "Chiffre d'affaires",
          definition: "Total des ventes de la periode",
          type: "Financier",
          unit: "Montant (FCFA / XOF)",
          formula: "Volume produit x Prix unitaire HT",
          target: "100",
          collectionFrequency: "Hebdomadaire Mensuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Personne fournissant la donnee",
          responsible: "GNIMAVO Sylvanus",
          respondent: "GNIMAVO Sylvanus",
          respondentFunction: "Controleur de gestion",
          year: "2026",
          hierarchicalValidation: "Non",
          validator: "",
          reference: "Soumission 1 / KPI 1",
          documentStatus: "A valider",
          attention: "Validation hierarchique requise",
        },
        {
          aliases: ["MTTR"],
          id: "KPI-010",
          title: "MTTR",
          definition: "QOS : Assurer l'amelioration de la satisfaction client",
          type: "Satisfaction Client",
          unit: "Minutes",
          formula: "Moyenne de temps de traitement de tous les tickets sur la periode",
          target: "60",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Systeme, fichier",
          responsible: "Responsable support et maintenance",
          respondent: "AGUIAH Leandre",
          respondentFunction: "Directeur des Systemes d'Information",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "KPI COPC",
          reference: "Soumission 2 / KPI 10",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Disponibilite systemes", "Taux de Disponibilite / Accessibilite"],
          id: "KPI-005",
          title: "Taux de Disponibilite / Accessibilite",
          definition: "Assurer la disponibilite de l'infrastructure",
          type: "Productivite",
          unit: "% (Pourcentage)",
          formula: "Nombre de minutes de disponibilite du commutateur x 100 / total des minutes de service ouvert",
          target: "98",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Systeme, fichier et personne",
          responsible: "Responsable Reseau & Systeme",
          respondent: "AGUIAH Leandre",
          respondentFunction: "Directeur des Systemes d'Information",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "KPI COPC",
          reference: "Soumission 2 / KPI 5",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Taux de recouvrement", "Recouvrement", "Recouvrement global"],
          id: "KPI-045",
          title: "Taux de recouvrement",
          definition: "Pourcentage de creances effectivement encaissees par rapport aux creances exigibles",
          type: "Financier",
          unit: "% (Pourcentage)",
          formula: "Somme des encaissements sur la periode / somme des creances exigibles sur la meme periode x 100",
          target: "75",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Fichier finances",
          responsible: "AKUEGNON EDNA-CHARLO",
          respondent: "AKUEGNON EDNA-CHARLO ASSEREOU",
          respondentFunction: "Responsable recouvrement groupe",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "Michele DEGBOE",
          reference: "Soumission 9 / KPI 45",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Taux d'occupation", "TAUX D'OCCUPATION"],
          id: "KPI-053",
          title: "TAUX D'OCCUPATION",
          definition: "Mesure le temps productif par rapport au temps total traite par les ressources WFM",
          type: "Productivite",
          unit: "% (Pourcentage)",
          formula: "Traitement + attente / Traitement + attente + post appel x 100",
          target: "75",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Extractions CX Insights / Hermes / Genesys / Nobelbiz",
          responsible: "ANAIS AHUIASSOU / ERICK AGBA",
          respondent: "ANAIS AHUIASSOU",
          respondentFunction: "Charge planification et reporting",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "JAMES MANGA",
          reference: "Soumission 10 / KPI 53",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Adherence au planning", "ADHERENCE PLANNING"],
          id: "KPI-054",
          title: "ADHERENCE PLANNING",
          definition: "Degre de respect des heures programmees par rapport aux heures planifiees",
          type: "Productivite",
          unit: "% (Pourcentage)",
          formula: "ETP effectif total planifie / besoin x 100",
          target: "90",
          collectionFrequency: "Hebdomadaire Mensuelle Trimestrielle Annuelle",
          reportingFrequency: "Hebdomadaire Mensuelle Trimestrielle Semestrielle Annuelle",
          dataSource: "Outil WFM et extractions CX Insights / Hermes / Genesys / Nobelbiz",
          responsible: "ANAIS AHUIASSOU / ERICK AGBA",
          respondent: "ANAIS AHUIASSOU",
          respondentFunction: "Charge planification et reporting",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "JAMES MANGA",
          reference: "Soumission 10 / KPI 54",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
        {
          aliases: ["Taux de service (SL)", "Taux de service client"],
          id: "KPI-061",
          title: "Taux de service client",
          definition: "Capacite du service a satisfaire les demandes des clients internes",
          type: "Satisfaction Client",
          unit: "% (Pourcentage)",
          formula: "Nombre de demandes satisfaites / nombre total de demandes exprimees x 100",
          target: "90",
          collectionFrequency: "Mensuelle",
          reportingFrequency: "Mensuelle",
          dataSource: "Formulaires de demande, tableaux de suivi des demandes, mails",
          responsible: "Responsable Achats et Moyens Generaux",
          respondent: "GANKPA Juste",
          respondentFunction: "Responsable Achats et Moyens Generaux",
          year: "2026",
          hierarchicalValidation: "Oui",
          validator: "Michele DEGBOE",
          reference: "Soumission 11 / KPI 61",
          documentStatus: "Documente",
          attention: "Aucun point bloquant identifie",
        },
      ],
    },

    koboConfiguredSources: [
      {
        role: "referentielKpi",
        serverUrl: "https://kf.kobotoolbox.org",
        formId: "agJCJ2VqwMGNk586NHJ39W",
        title: "PMS GMC - Formulaire 1 - Referentiel KPI et formules",
        mode: "KoboCollect Referentiel KPI",
        status: "Actif",
        detail: "KPI, objectifs et formules de calcul par pays / filiale et par pole.",
        mappedFields: {
          id: "id_kpi",
          branch: "pays_filiale",
          category: "categorie_organisationnelle",
          entity: "entite_direction",
          subEntity: "sous_entite_pole_filiale",
          pole: "groupe_de_rattachement",
          path: "chemin_organisationnel",
          title: "intitule_du_kpi",
          definition: "description_definition",
          type: "type_de_kpi",
          unit: "unite_de_mesure",
          formula: "formule_de_calcul",
          target: "valeur_cible",
          collectionFrequency: "frequence_de_collecte",
          reportingFrequency: "periodicite_du_reporting",
          sourceData: "source_de_la_donnee",
          owner: "responsable_du_kpi",
          respondent: "repondant",
          respondentFunction: "fonction_du_repondant",
          year: "annee",
          validation: "validation_hierarchique",
          validator: "validateur",
          comments: "commentaires",
          submittedAt: "date_de_soumission",
          sourceReference: "reference_source",
          documentStatus: "statut_documentaire",
          attention: "points_d_attention",
        },
      },
      {
        role: "donneesCalcul",
        serverUrl: "https://kf.kobotoolbox.org",
        formId: "aZ5JcFjcL9YvnQozqHWrqN",
        title: "PMS GMC - Formulaire 2 - Donnees de calcul journalieres",
        mode: "KoboCollect Donnees de calcul",
        status: "Actif",
        detail: "Elements bruts utilises pour calculer les KPI.",
        mappedFields: {
          pole: "pole_id",
          kpi: "id_kpi",
          period: "periode_reporting",
          element: "element_id",
          value: "valeur_element",
          branch: "filiale",
          date: "date_collecte",
          validation: "validation_hierarchique",
        },
      },
    ],

    countries: [
      { id: "Groupe", code: "GROUPE", name: "Groupe", score: 82, quality: 88, readiness: 74, kpiCount: 74, activePoles: 15, lateSubmissions: 0, status: "Consolide", className: "green" },
      { id: "CI", code: "CI", name: "Cote d'Ivoire", score: 88, quality: 92, readiness: 84, kpiCount: 74, activePoles: 15, lateSubmissions: 0, status: "Valide", className: "green" },
      { id: "BJ", code: "BJ", name: "Benin", score: 84, quality: 89, readiness: 80, kpiCount: 66, activePoles: 14, lateSubmissions: 0, status: "Valide", className: "green" },
      { id: "CM", code: "CM", name: "Cameroun", score: 79, quality: 86, readiness: 76, kpiCount: 66, activePoles: 14, lateSubmissions: 1, status: "A surveiller", className: "amber" },
      { id: "CG", code: "CG", name: "Congo", score: 73, quality: 81, readiness: 69, kpiCount: 66, activePoles: 14, lateSubmissions: 2, status: "A surveiller", className: "amber" },
      { id: "GN", code: "GN", name: "Guinee Conakry", score: 69, quality: 78, readiness: 64, kpiCount: 66, activePoles: 14, lateSubmissions: 2, status: "Plan requis", className: "red" },
      { id: "GW", code: "GW", name: "Guinee-Bissau", score: 62, quality: 74, readiness: 58, kpiCount: 66, activePoles: 14, lateSubmissions: 3, status: "Plan requis", className: "red" },
      { id: "NIG", code: "NIG", name: "Niger", score: 71, quality: 79, readiness: 66, kpiCount: 74, activePoles: 15, lateSubmissions: 1, status: "A surveiller", className: "amber" },
    ],

    poleCountryScopes: {
      BRD: ["Cote d'Ivoire", "Niger"],
    },

    branchScores: [
      { name: "Cote d'Ivoire", score: 88 },
      { name: "Benin", score: 84 },
      { name: "Cameroun", score: 79 },
      { name: "Congo", score: 73 },
      { name: "Guinee Conakry", score: 69 },
      { name: "Guinee-Bissau", score: 62 },
      { name: "Niger", score: 71 },
    ],

    groups: [
      { name: "AAIM", count: 13, validation: "100%", priority: "RAS" },
      { name: "DPB", count: 1, validation: "100%", priority: "RAS" },
      { name: "Hoope Cote d'Ivoire", count: 8, validation: "100%", priority: "RAS" },
      { name: "Hoope Niger", count: 4, validation: "0%", priority: "Validation a completer" },
      { name: "Pole Marketing et Communication", count: 10, validation: "0%", priority: "Validation a completer" },
      { name: "Pole Recouvrement", count: 7, validation: "100%", priority: "RAS" },
      { name: "Direction du Systeme Informatique", count: 10, validation: "100%", priority: "RAS" },
      { name: "Pole Moyens Generaux", count: 6, validation: "100%", priority: "RAS" },
      { name: "Pole Voix du Client & EPC", count: 7, validation: "100%", priority: "RAS" },
      { name: "Direction Finance et Comptabilite", count: 3, validation: "0%", priority: "Validation a completer" },
      { name: "Pole WFM", count: 5, validation: "100%", priority: "RAS" },
    ],

    methodologyControls: [
      {
        dimension: "Completude",
        question: "Toutes les donnees attendues sont presentes.",
        proof: "Valeurs manquantes et justification des absences",
        frequency: "A chaque collecte",
      },
      {
        dimension: "Validite",
        question: "Les formats, unites et domaines de valeurs sont respectes.",
        proof: "Types, bornes et listes autorisees",
        frequency: "A chaque collecte",
      },
      {
        dimension: "Coherence",
        question: "Les agregats et les evolutions sont plausibles.",
        proof: "Rapprochement avec le detail, le budget ou N-1",
        frequency: "A chaque reporting",
      },
      {
        dimension: "Exactitude",
        question: "La valeur reflete fidelement la source.",
        proof: "Echantillonnage ou recalcul independant",
        frequency: "Selon le risque",
      },
      {
        dimension: "Actualite",
        question: "La valeur est disponible dans le delai.",
        proof: "Date d'extraction et date de validation",
        frequency: "A chaque reporting",
      },
    ],

    collectionForms: [
      {
        code: "BPO",
        title: "Fiche BPO - Direction des operations",
        cadence: "Horaire / Journaliere",
        sourceSheet: "BPO",
        sections: ["Parametres de campagne", "SLA qualite et delai", "Appels recus / traites / abandonnes", "Agents presents et temps de production"],
      },
      {
        code: "DFC",
        title: "Fiche DFC - Finance & Controle de gestion",
        cadence: "Quotidienne / Mensuelle",
        sourceSheet: "DFC",
        sections: ["Parametres financiers previsionnels", "CA previsionnel", "MS/CA previsionnel", "Donnees financieres journalieres"],
      },
      {
        code: "WFM",
        title: "Fiche WFM - Workforce Management",
        cadence: "Horaire / Journaliere",
        sourceSheet: "WFM",
        sections: ["Objectifs de planification", "Heures planifiees et realisees", "Presence, absences et retards", "Temps communication / ACW / presence"],
      },
      {
        code: "DSI",
        title: "Fiche DSI - Systeme d'information",
        cadence: "Journaliere / Mensuelle",
        sourceSheet: "DSI",
        sections: ["Parametres infrastructure", "Disponibilite systeme", "Incidents P1/P2/P3", "Tickets et postes operationnels"],
      },
      {
        code: "DCH",
        title: "Fiche DCH - Capital humain",
        cadence: "Journaliere / Mensuelle",
        sourceSheet: "DCH",
        sections: ["Grille remunerations", "Masse salariale chargee", "Effectifs presents", "Absences, retards et mouvements"],
      },
      {
        code: "EPC",
        title: "Fiche EPC - Evaluation & pilotage qualite",
        cadence: "Hebdomadaire",
        sourceSheet: "POLE EPC",
        sections: ["Parametres qualite", "ECC / ECA / ECCo / ENC", "Score qualite", "Coaching et plans d'action"],
      },
      {
        code: "DCM",
        title: "Fiche DCM - Direction des comptes",
        cadence: "Hebdomadaire / Mensuelle",
        sourceSheet: "DCM",
        sections: ["Parametres contractuels", "Conformite MCB / DO", "SLA contractuels", "Malus et renouvellements"],
      },
    ],

    collectionCadenceByPole: {
      BPO: { cadence: "Horaire / Journaliere", primary: "Journalier", sourceSheet: "BPO", formCode: "BPO", expectedDelay: "J+0 / J+1", detail: "Donnees operationnelles et production appelee par tranche horaire puis consolidation journaliere." },
      PSMQ: { cadence: "Mensuelle / Trimestrielle", primary: "Mensuel", sourceSheet: "Catalogue KPI", formCode: "CATALOGUE", expectedDelay: "M+1", detail: "Indicateurs systeme qualite consolides depuis le referentiel KPI et controles documentaires." },
      WFM: { cadence: "Horaire / Journaliere", primary: "Journalier", sourceSheet: "WFM", formCode: "WFM", expectedDelay: "J+0 / J+1", detail: "Planification, presence, adherence et occupation suivies au fil de l'eau." },
      DRIVE: { cadence: "Hebdomadaire / Mensuelle", primary: "Hebdomadaire", sourceSheet: "Catalogue KPI", formCode: "PROJET", expectedDelay: "S+1", detail: "Avancement projet, jalons, risques et actions consolides chaque semaine." },
      COM: { cadence: "Hebdomadaire / Mensuelle", primary: "Hebdomadaire", sourceSheet: "Catalogue KPI", formCode: "COM", expectedDelay: "S+1 / M+1", detail: "Pipeline, conversion et signatures suivis par semaine puis consolides mensuellement." },
      DFC: { cadence: "Quotidienne / Mensuelle", primary: "Journalier", sourceSheet: "DFC", formCode: "DFC", expectedDelay: "J+1 / M+1", detail: "Suivi journalier du CA et consolidation mensuelle des indicateurs financiers." },
      REC: { cadence: "Hebdomadaire / Mensuelle", primary: "Hebdomadaire", sourceSheet: "Catalogue KPI", formCode: "REC", expectedDelay: "S+1 / M+1", detail: "Relances et portefeuille de recouvrement suivis par semaine, taux consolides au mois." },
      BRD: { cadence: "Journaliere / Mensuelle", primary: "Journalier", sourceSheet: "Catalogue KPI", formCode: "BRD", expectedDelay: "J+1 / M+1", detail: "Disponibilite reseau, ruptures et activite retail controlees au quotidien." },
      BID: { cadence: "Mensuelle", primary: "Mensuel", sourceSheet: "Catalogue KPI", formCode: "BID", expectedDelay: "M+1", detail: "Portefeuille innovation et developpement consolide sur les cycles projet mensuels." },
      DSI: { cadence: "Journaliere / Mensuelle", primary: "Journalier", sourceSheet: "DSI", formCode: "DSI", expectedDelay: "J+1", detail: "Disponibilite, incidents et tickets suivis en quotidien avec consolidation mensuelle." },
      DCH: { cadence: "Journaliere / Mensuelle", primary: "Journalier", sourceSheet: "DCH", formCode: "DCH", expectedDelay: "J+1 / M+1", detail: "Presence, absences et retards en quotidien, indicateurs RH consolides en mensuel." },
      EPC: { cadence: "Hebdomadaire", primary: "Hebdomadaire", sourceSheet: "POLE EPC", formCode: "EPC", expectedDelay: "S+1", detail: "Evaluations qualite, erreurs critiques et coaching consolides par semaine." },
      GDC: { cadence: "Hebdomadaire / Mensuelle", primary: "Hebdomadaire", sourceSheet: "DCM", formCode: "DCM", expectedDelay: "S+1 / M+1", detail: "Conformite contractuelle et SLA suivis par semaine avec consolidation mensuelle." },
      PAC: { cadence: "Journaliere / Mensuelle", primary: "Journalier", sourceSheet: "FORMULE", formCode: "CONSOLIDE", expectedDelay: "J+1 / M+1", detail: "Indicateurs consolides calcules a partir des donnees journalieres des poles sources." },
      PMG: { cadence: "Journaliere / Hebdomadaire / Mensuelle", primary: "Journalier", sourceSheet: "Catalogue KPI", formCode: "PMG", expectedDelay: "J+1 / S+1 / M+1", detail: "Disponibilite des moyens suivie au quotidien, demandes et inventaire consolides par periode." },
    },

    koboSubmissions: [
      { form: "KBO-BPO-JOUR-01", branch: "Cote d'Ivoire", kpi: "Taux de service (SL)", collector: "A. Traore", status: "Valide", className: "green" },
      { form: "KBO-WFM-JOUR-02", branch: "Congo", kpi: "Taux d'occupation", collector: "M. Nkoua", status: "En retard", className: "gray" },
      { form: "KBO-FIN-MENS-01", branch: "Benin", kpi: "Ratio MS/CA", collector: "S. Houngue", status: "Erreur mapping", className: "red" },
      { form: "KBO-RH-HEBD-01", branch: "Guinee Conakry", kpi: "Taux d'absenteisme", collector: "I. Diallo", status: "A valider", className: "amber" },
      { form: "KBO-QUAL-MENS-01", branch: "Cameroun", kpi: "Quality Score", collector: "L. Mbarga", status: "Valide", className: "green" },
      { form: "KBO-BRD-MENS-02", branch: "Niger", kpi: "Performance MRE", collector: "Equipe Hoope Niger", status: "A valider", className: "amber" },
    ],

    koboPipeline: [
      { title: "Reception Kobo", detail: "Webhook ou synchronisation planifiee depuis KoboToolbox.", count: "1 285", status: "Actif", className: "green" },
      { title: "Zone de controle", detail: "Doublons, formats, pieces jointes et champs obligatoires.", count: "17", status: "A traiter", className: "amber" },
      { title: "Mapping KPI", detail: "Rattachement formulaire, pole, filiale, periode et code KPI.", count: "44", status: "Regles", className: "green" },
      { title: "Calcul PMS", detail: "Application des formules et seuils RAG du catalogue.", count: "74", status: "Pret", className: "green" },
      { title: "Publication", detail: "Mise a jour tableau de bord, alertes et rapports par pole.", count: "7", status: "Cycles", className: "green" },
    ],

    validationQueue: [
      { id: "VAL-1024", form: "KBO-FIN-MENS-01", pole: "DFC", issue: "Ratio MS/CA hors seuil et piece justificative manquante", owner: "Analyste BI", status: "Critique", className: "red" },
      { id: "VAL-1025", form: "KBO-WFM-JOUR-02", pole: "WFM", issue: "Soumission Congo en retard de 24h", owner: "Responsable WFM", status: "Relance", className: "gray" },
      { id: "VAL-1026", form: "KBO-RH-HEBD-01", pole: "DCH", issue: "Ecart absenteisme a commenter avant rapport hebdomadaire", owner: "DRH", status: "A valider", className: "amber" },
      { id: "VAL-1027", form: "KBO-BPO-JOUR-01", pole: "BPO", issue: "Taux abandon rouge, plan d'action requis", owner: "Directeur operations", status: "Plan requis", className: "red" },
    ],

    formulaDictionary: [
      { id: "01", direction: "BPO", name: "Taux de service (SL)", category: "Qualite service", formula: "Nb appels traites dans le SLA / Nb appels recus x 100", usage: "Mesure la proportion d'appels traites dans le delai contractuel.", frequency: "Horaire", target: ">= 80-90%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "02", direction: "BPO", name: "Taux de decrochage", category: "Qualite service", formula: "Nb appels traites / Nb appels recus x 100", usage: "Proportion d'appels pris en charge.", frequency: "Horaire", target: ">= 95%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "03", direction: "BPO", name: "Taux d'abandon", category: "Qualite service", formula: "Nb appels abandonnes / Nb appels recus x 100", usage: "Appels raccroches avant prise en charge.", frequency: "Horaire", target: "<= 5%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "04", direction: "BPO", name: "DMT - Duree Moyenne de Traitement (sec)", category: "Performance agent", formula: "(Temps communication + Temps ACW) / Nb appels traites", usage: "Temps moyen passe par appel.", frequency: "Journalier", target: "Selon contrat", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "05", direction: "BPO", name: "Taux de facturation", category: "Financier", formula: "Nb appels/interactions facturables / Nb appels/interactions traitees x 100", usage: "Part de la production effectivement facturable au client.", frequency: "Journalier", target: ">= 85-95%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "06", direction: "BPO", name: "CA de l'heure (FCFA/h)", category: "Financier", formula: "CA realise / Heures de production realisees", usage: "Productivite financiere horaire.", frequency: "Horaire / Jour", target: "Selon objectif", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "07", direction: "BPO", name: "CA par agent par jour (FCFA)", category: "Financier", formula: "CA journalier / Nb agents presents", usage: "Productivite financiere individuelle.", frequency: "Journalier", target: "Selon objectif", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "08", direction: "BPO", name: "Performance horaire par agent (FCFA/h/agent)", category: "Financier", formula: "CA journalier / (Nb agents x Heures produites)", usage: "Productivite croisee agent x heure.", frequency: "Journalier", target: "Selon objectif", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "09", direction: "BPO", name: "Taux d'atteinte CA (%)", category: "Financier", formula: "CA realise / CA objectif x 100", usage: "Avancement par rapport a l'objectif journalier.", frequency: "Horaire / Jour", target: ">= 100%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "10", direction: "BPO", name: "Niveau de malus / % CA (%)", category: "Financier", formula: "Montant malus / CA brut x 100", usage: "Impact financier des non-conformites.", frequency: "Journalier", target: "<= seuil contrat", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "11", direction: "BPO", name: "CA net apres malus (FCFA)", category: "Financier", formula: "CA brut realise - Malus applicables", usage: "CA effectivement facture.", frequency: "Journalier", target: "CA brut idealement", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "12", direction: "BPO", name: "Nb portefeuilles actifs (CA > 0)", category: "Activite", formula: "COUNTIF(CA portefeuilles, '>0')", usage: "Campagnes en production effective.", frequency: "Journalier", target: "Nb total portefeuilles", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "13", direction: "WFM", name: "Taux d'occupation / Occupancy (%)", category: "WFM", formula: "Temps en communication + ACW / Temps de presence x 100", usage: "Taux d'utilisation reelle des agents.", frequency: "Horaire", target: "75-85%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "14", direction: "WFM", name: "Adherence au planning (%)", category: "WFM", formula: "Heures realisees conformement au schedule / Heures planifiees x 100", usage: "Respect des heures programmees.", frequency: "Journalier", target: ">= 85-90%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "15", direction: "WFM", name: "Shrinkage - Coefficient d'absenteisme WFM (%)", category: "WFM", formula: "Heures non productives / Heures planifiees x 100", usage: "Correction appliquee au dimensionnement.", frequency: "Journalier", target: "<= 20%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "16", direction: "WFM", name: "Taux de presence vs planning (%)", category: "WFM", formula: "Nb agents presents / Nb agents planifies x 100", usage: "Presence reelle face aux effectifs planifies.", frequency: "Journalier", target: ">= 95%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "18", direction: "WFM", name: "Productivite planifiee (FCFA/h/agent plan.)", category: "WFM x Financier", formula: "CA journalier / (Nb agents planifies x Heures planifiees)", usage: "Efficacite du dimensionnement WFM.", frequency: "Journalier", target: "Selon objectif", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "19", direction: "DCH", name: "Taux d'absenteisme (%)", category: "RH", formula: "Nb agents absents / Effectif theorique x 100", usage: "Impact RH direct sur la production.", frequency: "Journalier", target: "<= 5%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "20", direction: "DCH", name: "Taux de ponctualite (%)", category: "RH", formula: "(Nb presents - Nb retards) / Nb presents x 100", usage: "Discipline horaire des equipes.", frequency: "Journalier", target: ">= 95%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "21", direction: "DCH", name: "Taux de turn-over mensuel (%)", category: "RH", formula: "Nb sorties du mois / Effectif moyen du mois x 100", usage: "Stabilite des equipes.", frequency: "Mensuel", target: "<= 5%/mois", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "22", direction: "DCH", name: "Taux de turn-over annualise (%)", category: "RH", formula: "Taux de turn-over mensuel x 12", usage: "Vision annualisee du renouvellement des effectifs.", frequency: "Mensuel", target: "<= 25-30%/an", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "23", direction: "DCH", name: "Ratio MS/CA (%)", category: "RH x Financier", formula: "Masse salariale totale chargee / CA realise x 100", usage: "Efficacite de transformation de la masse salariale en CA.", frequency: "Mensuel", target: "<= 60-65%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "24", direction: "DCH", name: "Cout moyen par agent (FCFA/agent/mois)", category: "RH x Financier", formula: "MS totale chargee / Effectif total", usage: "Base de calcul du point mort.", frequency: "Mensuel", target: "Selon grille", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "25", direction: "DCH", name: "Ratio encadrement (agents / superviseur)", category: "RH", formula: "Nb CRCD / Nb superviseurs", usage: "Taux d'encadrement operationnel.", frequency: "Mensuel", target: "15-18 CRCD/supv.", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "26", direction: "POLE EPC", name: "Tx% ECC - Erreur Critique Client (%)", category: "Qualite", formula: "Nb erreurs critiques clients / Nb total evaluations x 100", usage: "Erreurs impactant directement l'experience client.", frequency: "Hebdo", target: "<= 5%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "27", direction: "POLE EPC", name: "Tx% ECA - Erreur Critique Agent (%)", category: "Qualite", formula: "Nb erreurs critiques agent / Nb total evaluations x 100", usage: "Erreurs de comportement agent.", frequency: "Hebdo", target: "<= 3%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "28", direction: "POLE EPC", name: "Tx% ECCo - Erreur Critique Conformite (%)", category: "Qualite", formula: "Nb erreurs critiques conformite / Nb total evaluations x 100", usage: "Erreurs de non-conformite reglementaire.", frequency: "Hebdo", target: "<= 2%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "29", direction: "POLE EPC", name: "Tx% ENC - Erreur Non Critique (%)", category: "Qualite", formula: "Nb erreurs non critiques / Nb total evaluations x 100", usage: "Erreurs sans impact immediat sur le client.", frequency: "Hebdo", target: "<= 10%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "30", direction: "POLE EPC", name: "Taux de defaut global (%)", category: "Qualite", formula: "Total erreurs / Nb total evaluations x 100", usage: "Indicateur synthetique de la qualite.", frequency: "Hebdo", target: "<= 15%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "31", direction: "POLE EPC", name: "Taux d'escalade / Pert Escal (%)", category: "Qualite", formula: "Nb appels escalades / Nb total appels traites x 100", usage: "Appels necessitant une intervention superieure.", frequency: "Hebdo", target: "<= 5%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "32", direction: "POLE EPC", name: "Score qualite moyen (%)", category: "Qualite", formula: "Somme des scores / Nb evaluations x 100", usage: "Notation moyenne sur grille EPC.", frequency: "Hebdo", target: ">= 85%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "33", direction: "DCM", name: "Taux de conformite MCB -> DO (%)", category: "Conformite", formula: "Nb obligations MCB conformes / Nb total obligations MCB x 100", usage: "Respect des engagements envers le client.", frequency: "Hebdo", target: ">= 90%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "34", direction: "DCM", name: "Taux de conformite DO -> MCB (%)", category: "Conformite", formula: "Nb obligations DO conformes / Nb total obligations DO x 100", usage: "Respect des engagements du client envers nous.", frequency: "Hebdo", target: ">= 85%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "35", direction: "DCM", name: "Taux SLA respect MCB (%)", category: "Conformite", formula: "Nb SLA MCB respectes / Nb total SLA MCB x 100", usage: "Respect des niveaux de service contractuels.", frequency: "Hebdo", target: ">= 95%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "36", direction: "DCM", name: "Malus en % du CA (%)", category: "Financier", formula: "Montant malus / CA brut x 100", usage: "Impact financier des non-conformites.", frequency: "Hebdo / Mois", target: "<= seuil contrat", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "37", direction: "DSI", name: "Taux de disponibilite systeme (%)", category: "IT", formula: "(Duree totale - Duree d'indisponibilite) / Duree totale x 100", usage: "Disponibilite des systemes de production.", frequency: "Journalier", target: ">= 99,5%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "38", direction: "DSI", name: "Taux de resolution J0 (%)", category: "IT", formula: "Nb tickets resolus J0 / Nb tickets ouverts J0 x 100", usage: "Reactivite du support IT.", frequency: "Journalier", target: ">= 70%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "39", direction: "DSI", name: "Taux postes operationnels (%)", category: "IT", formula: "(Nb postes total - Nb postes HS) / Nb postes total x 100", usage: "Disponibilite des equipements de production.", frequency: "Journalier", target: ">= 99%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "40", direction: "DSI", name: "MTTR - Mean Time to Repair (min)", category: "IT", formula: "Duree totale reparations / Nb incidents resolus", usage: "Temps moyen de reparation.", frequency: "Mensuel", target: "<= 30 min (P1)", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "41", direction: "CONSOLIDE", name: "Point mort CA / agent / jour (FCFA)", category: "Financier consolide", formula: "MS journaliere totale chargee / Nb agents presents", usage: "CA minimum par agent pour couvrir le cout.", frequency: "Journalier", target: "Calcul interne", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "42", direction: "CONSOLIDE", name: "Marge brute par portefeuille (FCFA)", category: "Financier consolide", formula: "CA net portefeuille - Charges directes imputees au portefeuille", usage: "Rentabilite reelle par campagne.", frequency: "Mensuel", target: "> 0 FCFA", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "43", direction: "CONSOLIDE", name: "Cout de production a l'heure (FCFA/h)", category: "Financier consolide", formula: "(MS directe + Charges operationnelles directes) / Heures produites", usage: "Cout horaire de production.", frequency: "Journalier", target: "< CA/h", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "44", direction: "CONSOLIDE", name: "Taux de productivite global (%)", category: "Performance globale", formula: "CA realise / CA potentiel theorique x 100", usage: "Efficacite globale du dispositif.", frequency: "Journalier", target: ">= 85%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
      { id: "45", direction: "CONSOLIDE", name: "Indice de performance composite (IPC)", category: "Performance globale", formula: "(Taux SL + Taux facturation + Taux adherence + Score qualite) / 4", usage: "Synthese service, finance, WFM et qualite.", frequency: "Journalier", target: ">= 85%", source: "GMC_FICHE_COLLECTE_V2.xlsx / FORMULE" },
    ],

    alerts: [
      {
        title: "Ratio MS/CA superieur au seuil",
        scope: "DFC - Cote d'Ivoire",
        detail: "65% sur la periode courante, plan de redressement requis sous 3 jours.",
        level: "red",
      },
      {
        title: "Taux d'appels facturables < 80%",
        scope: "BU BPO - Cameroun",
        detail: "Trois tranches horaires consecutives sous objectif, escalade Qualite + Supervision.",
        level: "red",
      },
      {
        title: "Absence de soumission J+1",
        scope: "WFM - Congo",
        detail: "Le formulaire Kobo journalier n'a pas ete synchronise depuis 24h.",
        level: "gray",
      },
      {
        title: "NPS en recul",
        scope: "Voix du Client - Groupe",
        detail: "Baisse de 7 points vs trimestre precedent, analyse IA recommandee.",
        level: "amber",
      },
    ],

    actionPlans: [
      { title: "Reduire le ratio MS/CA", owner: "DFC + DCH", due: "30/07/2026", progress: 45, detail: "Revue staffing indirect, gel remplacements non critiques et suivi hebdomadaire." },
      { title: "Augmenter les appels facturables", owner: "BU BPO + Qualite", due: "12/07/2026", progress: 68, detail: "Correction codification motifs, coaching short calls et controle qualite quotidien." },
      { title: "Rattraper collecte WFM Congo", owner: "WFM Congo", due: "08/07/2026", progress: 25, detail: "Relance collecteurs, verification smartphones offline et re-synchronisation Kobo." },
    ],

    reports: [
      { title: "Rapport COMEX Word", detail: "Narratif executif, tableaux KPI, alertes et plans d'action.", format: "DOCX" },
      { title: "Slides Performance Groupe", detail: "Synthese IPG, RAG, tendances et benchmark filiales.", format: "PPTX" },
      { title: "Base KPI Consolidee", detail: "Donnees brutes, calculs, controles qualite et mapping Kobo.", format: "XLSX" },
      { title: "Archive mensuelle", detail: "Version figee pour diffusion et historique audit.", format: "PDF" },
      { title: "Email hebdomadaire", detail: "Resume HTML automatique des KPIs et alertes prioritaires.", format: "EMAIL" },
      { title: "Rapport pertes CA", detail: "Pertes par source, tranche horaire, filiale et responsable.", format: "PPTX" },
    ],

    reporting: {
      defaultPole: "BPO",
      defaultCycle: "Journalier",
      cycles: [
        { value: "Journalier", deadline: "J+1 avant 10h00", scope: "Controle des collectes journalieres, anomalies et points bloquants" },
        { value: "Hebdomadaire", deadline: "Lundi 08h00", scope: "Suivi operationnel, alertes et actions court terme" },
        { value: "Mensuel", deadline: "05 du mois M+1", scope: "Rapport direction, COMEX et consolidation filiale" },
        { value: "Trimestriel", deadline: "10 du mois suivant", scope: "Analyse strategique, benchmark et trajectoire" },
        { value: "Semestriel", deadline: "15 du 7e / 1er mois", scope: "Revue maturite et amelioration continue" },
        { value: "Annuel", deadline: "31 janvier N+1", scope: "Bilan groupe, actionnaires et audit" },
      ],
      poles: [
        { id: "DFC", category: "Direction Generale", name: "Direction Finance & Comptabilite", owner: "Directeur financier", kpiCount: 3, score: 66, rag: "red", quality: 76, lastReport: "Juin 2026", status: "Plan requis", lateSubmissions: 3, actionCount: 5, readiness: 61 },
        { id: "PSMQ", category: "Direction Generale", name: "Pole Systeme de Management de la Qualite", owner: "Responsable qualite", kpiCount: 6, score: 82, rag: "green", quality: 91, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 88 },
        { id: "WFM", category: "Direction Generale", name: "Pole WFM", owner: "Responsable WFM", kpiCount: 5, score: 84, rag: "green", quality: 89, lastReport: "S27 2026", status: "Brouillon", lateSubmissions: 2, actionCount: 2, readiness: 78 },
        { id: "DRIVE", category: "Direction Generale", name: "Pole Projet DRIVE", owner: "Chef projet DRIVE", kpiCount: 5, score: 79, rag: "amber", quality: 87, lastReport: "Juin 2026", status: "En cours", lateSubmissions: 1, actionCount: 3, readiness: 73 },
        { id: "COM", category: "DGA Business & Expansion", name: "Pole Commercial", owner: "Responsable commercial", kpiCount: 4, score: 72, rag: "amber", quality: 83, lastReport: "Juin 2026", status: "A completer", lateSubmissions: 1, actionCount: 3, readiness: 70 },
        { id: "GDC", category: "DGA Business & Expansion", name: "Pole Gestionnaire de Compte", owner: "Responsable comptes", kpiCount: 4, score: 75, rag: "amber", quality: 84, lastReport: "Juin 2026", status: "A valider", lateSubmissions: 1, actionCount: 2, readiness: 76 },
        { id: "REC", category: "DGA Business & Expansion", name: "Pole Recouvrement", owner: "Responsable recouvrement", kpiCount: 7, score: 69, rag: "red", quality: 80, lastReport: "Juin 2026", status: "Plan requis", lateSubmissions: 2, actionCount: 5, readiness: 64 },
        { id: "BRD", category: "DGA Business & Expansion", name: "BU Retail & Distribution", owner: "Directeur retail", kpiCount: 8, score: 77, rag: "amber", quality: 86, lastReport: "Juin 2026", status: "En cours", lateSubmissions: 1, actionCount: 3, readiness: 75, note: "Hoope CI et Niger" },
        { id: "BPO", category: "DGA Business & Expansion", name: "BU BPO", owner: "Directeur des operations", kpiCount: 12, score: 78, rag: "amber", quality: 92, lastReport: "S27 2026", status: "A valider", lateSubmissions: 1, actionCount: 4, readiness: 86 },
        { id: "BID", category: "DGA Business & Expansion", name: "BU Innovation & Developpement", owner: "Directeur innovation", kpiCount: 8, score: 80, rag: "green", quality: 88, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 85, note: "AAIM, DPB, SCI" },
        { id: "PAC", category: "DGA Support & Performance", name: "Pole Performance & Amelioration Continue", owner: "Responsable performance", kpiCount: 6, score: 83, rag: "green", quality: 90, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 89 },
        { id: "EPC", category: "DGA Support & Performance", name: "Pole Voix du Client & EPC", owner: "Responsable EPC", kpiCount: 7, score: 81, rag: "green", quality: 90, lastReport: "T2 2026", status: "Valide", lateSubmissions: 0, actionCount: 2, readiness: 91 },
        { id: "DSI", category: "DGA Support & Performance", name: "Direction Systeme Informatique", owner: "DSI", kpiCount: 10, score: 88, rag: "green", quality: 94, lastReport: "Juin 2026", status: "Valide", lateSubmissions: 0, actionCount: 1, readiness: 96 },
        { id: "DCH", category: "DGA Support & Performance", name: "Direction Capital Humain", owner: "DRH", kpiCount: 7, score: 73, rag: "amber", quality: 85, lastReport: "S27 2026", status: "En cours", lateSubmissions: 1, actionCount: 3, readiness: 74 },
        { id: "PMG", category: "DGA Support & Performance", name: "Pole Moyens Generaux", owner: "Responsable moyens generaux", kpiCount: 6, score: 76, rag: "amber", quality: 84, lastReport: "Juin 2026", status: "A valider", lateSubmissions: 1, actionCount: 2, readiness: 77 },
      ],
      kpisByPole: {
        BPO: [
          { name: "Taux de service (SL)", value: "78%", target: ">= 80-90%", trend: "-2 pts", status: "amber", source: "KBO-BPO-JOUR-01" },
          { name: "Taux d'abandon", value: "6.8%", target: "<= 5%", trend: "+1.1 pt", status: "red", source: "KBO-BPO-JOUR-01" },
          { name: "Taux de facturation", value: "87%", target: ">= 85-95%", trend: "+4 pts", status: "green", source: "KBO-HORAIRE-JOUR-03" },
          { name: "CA de l'heure", value: "1.9M FCFA", target: "Selon objectif", trend: "-8%", status: "amber", source: "KBO-HORAIRE-JOUR-03" },
        ],
        WFM: [
          { name: "Taux d'occupation", value: "82%", target: "75-85%", trend: "+3 pts", status: "green", source: "KBO-WFM-JOUR-02" },
          { name: "Adherence au planning", value: "88%", target: ">= 85-90%", trend: "+1 pt", status: "green", source: "KBO-WFM-JOUR-02" },
          { name: "Shrinkage", value: "18%", target: "<= 20%", trend: "-2 pts", status: "green", source: "KBO-WFM-JOUR-02" },
        ],
        DFC: [
          { name: "Ratio MS/CA", value: "65%", target: "<= 45%", trend: "+7 pts", status: "red", source: "KBO-FIN-MENS-01" },
          { name: "Chiffre d'affaires", value: "412M FCFA", target: "Objectif mensuel", trend: "-9%", status: "amber", source: "KBO-FIN-MENS-01" },
          { name: "Recouvrement", value: "73%", target: ">= 85%", trend: "-4 pts", status: "red", source: "KBO-FIN-MENS-01" },
        ],
        PSMQ: [
          { name: "Taux conformite processus", value: "91%", target: ">= 90%", trend: "+3 pts", status: "green", source: "KBO-QUAL-PROC-01" },
          { name: "Actions correctives cloturees", value: "84%", target: ">= 85%", trend: "-1 pt", status: "amber", source: "KBO-QUAL-PROC-01" },
          { name: "Audits internes realises", value: "96%", target: ">= 95%", trend: "+4 pts", status: "green", source: "KBO-QUAL-AUDIT-01" },
        ],
        DRIVE: [
          { name: "Jalons projet tenus", value: "78%", target: ">= 85%", trend: "-5 pts", status: "amber", source: "KBO-DRIVE-MENS-01" },
          { name: "Livrables valides", value: "82%", target: ">= 80%", trend: "+6 pts", status: "green", source: "KBO-DRIVE-MENS-01" },
          { name: "Risques ouverts", value: "6", target: "<= 3", trend: "+2", status: "red", source: "KBO-DRIVE-RISK-01" },
        ],
        DCH: [
          { name: "Taux d'absenteisme", value: "5.8%", target: "<= 5%", trend: "+0.6 pt", status: "amber", source: "KBO-RH-HEBD-01" },
          { name: "Taux de presence", value: "94%", target: ">= 95%", trend: "-1 pt", status: "amber", source: "KBO-RH-HEBD-01" },
          { name: "Turnover mensuel", value: "3.9%", target: "<= cible", trend: "stable", status: "green", source: "KBO-RH-HEBD-01" },
        ],
        DSI: [
          { name: "Disponibilite systemes", value: "99.7%", target: ">= 99.5%", trend: "+0.1 pt", status: "green", source: "KBO-DSI-JOUR-01" },
          { name: "MTTR", value: "3h20", target: "<= 4h", trend: "-35 min", status: "green", source: "KBO-DSI-JOUR-01" },
          { name: "Incidents securite", value: "2", target: "0 critique", trend: "-1", status: "amber", source: "KBO-DSI-JOUR-01" },
        ],
        EPC: [
          { name: "Quality Score", value: "86%", target: ">= 85%", trend: "+2 pts", status: "green", source: "KBO-QUAL-MENS-01" },
          { name: "CSAT", value: "82%", target: ">= 85%", trend: "-3 pts", status: "amber", source: "KBO-QUAL-MENS-01" },
          { name: "Reclamations J+1", value: "74%", target: ">= 70%", trend: "+5 pts", status: "green", source: "KBO-QUAL-MENS-01" },
        ],
        DCM: [
          { name: "Taux de conversion", value: "17%", target: ">= 20%", trend: "-2 pts", status: "amber", source: "KBO-DCM-HEBD-01" },
          { name: "Pipeline commercial", value: "81%", target: ">= 100%", trend: "+6 pts", status: "amber", source: "KBO-DCM-HEBD-01" },
          { name: "Recouvrement global", value: "79%", target: ">= 85%", trend: "-1 pt", status: "amber", source: "KBO-DCM-HEBD-01" },
        ],
        COM: [
          { name: "Taux de conversion", value: "17%", target: ">= 20%", trend: "-2 pts", status: "amber", source: "KBO-COM-HEBD-01" },
          { name: "Nouveaux contrats signes", value: "11", target: "15", trend: "+2", status: "amber", source: "KBO-COM-HEBD-01" },
          { name: "Pipeline qualifie", value: "81%", target: ">= 90%", trend: "+6 pts", status: "amber", source: "KBO-COM-PIPE-01" },
        ],
        GDC: [
          { name: "Taux renouvellement comptes", value: "88%", target: ">= 85%", trend: "+3 pts", status: "green", source: "KBO-GDC-MENS-01" },
          { name: "Satisfaction comptes cles", value: "82%", target: ">= 85%", trend: "-2 pts", status: "amber", source: "KBO-GDC-MENS-01" },
          { name: "Plans comptes a jour", value: "76%", target: ">= 80%", trend: "+4 pts", status: "amber", source: "KBO-GDC-PLAN-01" },
        ],
        REC: [
          { name: "Taux de recouvrement", value: "73%", target: ">= 85%", trend: "-4 pts", status: "red", source: "KBO-REC-MENS-01" },
          { name: "Creances > 90 jours", value: "18%", target: "<= 10%", trend: "+3 pts", status: "red", source: "KBO-REC-MENS-01" },
          { name: "Dossiers relances", value: "91%", target: ">= 90%", trend: "+5 pts", status: "green", source: "KBO-REC-HEBD-01" },
        ],
        BRD: [
          { name: "CA retail", value: "94%", target: ">= 100%", trend: "+4 pts", status: "amber", source: "KBO-BRD-MENS-01" },
          { name: "Disponibilite points de vente", value: "97%", target: ">= 95%", trend: "+1 pt", status: "green", source: "KBO-BRD-JOUR-01" },
          { name: "Ruptures critiques", value: "5", target: "0 critique", trend: "-2", status: "amber", source: "KBO-BRD-STOCK-01" },
        ],
        BID: [
          { name: "Taux avancement projets", value: "86%", target: ">= 80%", trend: "+7 pts", status: "green", source: "KBO-BID-MENS-01" },
          { name: "Projets en retard", value: "2", target: "<= 2", trend: "stable", status: "green", source: "KBO-BID-MENS-01" },
          { name: "ROI initiatives", value: "71%", target: ">= 75%", trend: "+3 pts", status: "amber", source: "KBO-BID-ROI-01" },
        ],
        PAC: [
          { name: "Taux plans actions clotures", value: "89%", target: ">= 85%", trend: "+6 pts", status: "green", source: "KBO-PAC-MENS-01" },
          { name: "Gains productivite", value: "7.5%", target: ">= 5%", trend: "+1.2 pt", status: "green", source: "KBO-PAC-MENS-01" },
          { name: "Chantiers en retard", value: "3", target: "<= 2", trend: "+1", status: "amber", source: "KBO-PAC-HEBD-01" },
        ],
        PMG: [
          { name: "Disponibilite moyens", value: "92%", target: ">= 95%", trend: "-2 pts", status: "amber", source: "KBO-PMG-JOUR-01" },
          { name: "Delai traitement demandes", value: "3.8j", target: "<= 3j", trend: "+0.4j", status: "amber", source: "KBO-PMG-HEBD-01" },
          { name: "Conformite inventaire", value: "96%", target: ">= 95%", trend: "+2 pts", status: "green", source: "KBO-PMG-MENS-01" },
        ],
      },
      workflow: [
        { step: "1. Collecte Kobo", detail: "Soumissions terrain synchronisees et controlees." },
        { step: "2. Consolidation KPI", detail: "Calculs, RAG, tendances et donnees manquantes." },
        { step: "3. Commentaire pole", detail: "Causes, faits marquants et plan d'action SMART." },
        { step: "4. Validation N+1", detail: "Visa direction / DGA avant diffusion." },
        { step: "5. Export & diffusion", detail: "Word, PDF, PowerPoint, Excel ou email planifie." },
      ],
      checklist: [
        { key: "Donnees Kobo synchronisees", owner: "Responsable collecte" },
        { key: "Controle completude et validite", owner: "Analyste BI" },
        { key: "Commentaires sur KPI orange/rouge", owner: "Responsable pole" },
        { key: "Plan d'action SMART rattache", owner: "Directeur fonctionnel" },
        { key: "Validation N+1 avant diffusion", owner: "DGA / DG" },
      ],
      calendar: [
        { pole: "BPO", cycle: "Hebdomadaire", period: "S28 2026", due: "13/07/2026 08:00", status: "A valider", owner: "Directeur des operations" },
        { pole: "WFM", cycle: "Hebdomadaire", period: "S28 2026", due: "13/07/2026 08:00", status: "Brouillon", owner: "Responsable WFM" },
        { pole: "DFC", cycle: "Mensuel", period: "Juin 2026", due: "05/07/2026 18:00", status: "Plan requis", owner: "Directeur financier" },
        { pole: "DCH", cycle: "Hebdomadaire", period: "S28 2026", due: "13/07/2026 08:00", status: "En cours", owner: "DRH" },
        { pole: "DSI", cycle: "Mensuel", period: "Juin 2026", due: "05/07/2026 18:00", status: "Valide", owner: "DSI" },
        { pole: "EPC", cycle: "Trimestriel", period: "T2 2026", due: "10/07/2026 18:00", status: "Valide", owner: "Responsable EPC" },
        { pole: "DCM", cycle: "Mensuel", period: "Juin 2026", due: "05/07/2026 18:00", status: "A completer", owner: "Directeur commercial" },
      ],
      distribution: [
        { audience: "Responsable pole", channel: "In-app + email", timing: "Avant validation", status: "Actif", className: "green" },
        { audience: "Direction fonctionnelle", channel: "PDF signe", timing: "Apres validation N+1", status: "A valider", className: "amber" },
        { audience: "COMEX / DG", channel: "Word COMEX + slides", timing: "Selon calendrier", status: "Planifie", className: "green" },
        { audience: "Archive audit", channel: "PDF + Excel donnees", timing: "A chaque cloture", status: "Actif", className: "green" },
      ],
      history: [
        { id: "RPT-2026-S27-BPO", pole: "BPO", cycle: "Hebdomadaire", period: "S27 2026", format: "Word COMEX", status: "Valide", generatedAt: "06/07/2026 08:14" },
        { id: "RPT-2026-06-DFC", pole: "DFC", cycle: "Mensuel", period: "Juin 2026", format: "PDF signe", status: "Plan requis", generatedAt: "05/07/2026 17:22" },
        { id: "RPT-2026-T2-EPC", pole: "EPC", cycle: "Trimestriel", period: "T2 2026", format: "PowerPoint synthese", status: "Valide", generatedAt: "04/07/2026 11:05" },
      ],
    },

    roles: [
      ["Super Administrateur", "Groupe", "Oui", "Oui", "Total"],
      ["Administrateur Categorie", "Categorie", "Oui", "Oui", "Partiel"],
      ["Directeur Fonctionnel", "Direction", "Oui", "N+1", "Non"],
      ["Responsable Pole", "Pole", "Oui", "Non", "Non"],
      ["Analyste BI", "Groupe", "Non", "Non", "Exports"],
      ["COMEX / DG", "Groupe", "Non", "Non", "Lecture"],
      ["Auditeur externe", "Limite", "Non", "Non", "Temporaire"],
    ],

    auditTrail: [
      "08:42 - Sync Kobo KBO-BPO-JOUR-01 integree",
      "08:33 - Seuil Ratio MS/CA modifie par Admin",
      "08:12 - Plan d'action BPO valide par DGA",
      "07:58 - Rejet doublon formulaire WFM Congo",
    ],
  };

  window.PMS_DATA = data;
})();
